/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppPlayerRouteImport } from './routes/_app/player'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppOrgsIndexRouteImport } from './routes/_app/orgs/index'
import { Route as ApiV1OpenapiDotyamlRouteImport } from './routes/api/v1/openapi[.]yaml'
import { Route as ApiV1OpenapiDotjsonRouteImport } from './routes/api/v1/openapi[.]json'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1OrganizationsIndexRouteImport } from './routes/api/v1/organizations/index'
import { Route as AppOrgsOrgIdIndexRouteImport } from './routes/_app/orgs/$orgId/index'
import { Route as ApiV1OrganizationsPostAuthDestinationRouteImport } from './routes/api/v1/organizations/post-auth-destination'
import { Route as ApiV1OrganizationsMineRouteImport } from './routes/api/v1/organizations/mine'
import { Route as ApiV1MetaPingRouteImport } from './routes/api/v1/meta/ping'
import { Route as ApiV1IdentityOnboardingRouteImport } from './routes/api/v1/identity/onboarding'
import { Route as ApiV1OrganizationsInvitationsAcceptRouteImport } from './routes/api/v1/organizations/invitations.accept'
import { Route as ApiV1OrganizationsOrganizationIdInvitationsRouteImport } from './routes/api/v1/organizations/$organizationId.invitations'
import { Route as ApiV1GameDataClubsSearchRouteImport } from './routes/api/v1/game-data/clubs/search'
import { Route as ApiV1GameDataClubsExternalClubIdRouteImport } from './routes/api/v1/game-data/clubs/$externalClubId'
import { Route as ApiV1GameDataClubsExternalClubIdMatchesRouteImport } from './routes/api/v1/game-data/clubs/$externalClubId.matches'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppPlayerRoute = AppPlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgsIndexRoute = AppOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => AppRoute,
} as any)
const ApiV1OpenapiDotyamlRoute = ApiV1OpenapiDotyamlRouteImport.update({
  id: '/api/v1/openapi.yaml',
  path: '/api/v1/openapi.yaml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OpenapiDotjsonRoute = ApiV1OpenapiDotjsonRouteImport.update({
  id: '/api/v1/openapi.json',
  path: '/api/v1/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OrganizationsIndexRoute = ApiV1OrganizationsIndexRouteImport.update({
  id: '/api/v1/organizations/',
  path: '/api/v1/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrgsOrgIdIndexRoute = AppOrgsOrgIdIndexRouteImport.update({
  id: '/orgs/$orgId/',
  path: '/orgs/$orgId/',
  getParentRoute: () => AppRoute,
} as any)
const ApiV1OrganizationsPostAuthDestinationRoute =
  ApiV1OrganizationsPostAuthDestinationRouteImport.update({
    id: '/api/v1/organizations/post-auth-destination',
    path: '/api/v1/organizations/post-auth-destination',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1OrganizationsMineRoute = ApiV1OrganizationsMineRouteImport.update({
  id: '/api/v1/organizations/mine',
  path: '/api/v1/organizations/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MetaPingRoute = ApiV1MetaPingRouteImport.update({
  id: '/api/v1/meta/ping',
  path: '/api/v1/meta/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1IdentityOnboardingRoute = ApiV1IdentityOnboardingRouteImport.update({
  id: '/api/v1/identity/onboarding',
  path: '/api/v1/identity/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OrganizationsInvitationsAcceptRoute =
  ApiV1OrganizationsInvitationsAcceptRouteImport.update({
    id: '/api/v1/organizations/invitations/accept',
    path: '/api/v1/organizations/invitations/accept',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1OrganizationsOrganizationIdInvitationsRoute =
  ApiV1OrganizationsOrganizationIdInvitationsRouteImport.update({
    id: '/api/v1/organizations/$organizationId/invitations',
    path: '/api/v1/organizations/$organizationId/invitations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1GameDataClubsSearchRoute =
  ApiV1GameDataClubsSearchRouteImport.update({
    id: '/api/v1/game-data/clubs/search',
    path: '/api/v1/game-data/clubs/search',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1GameDataClubsExternalClubIdRoute =
  ApiV1GameDataClubsExternalClubIdRouteImport.update({
    id: '/api/v1/game-data/clubs/$externalClubId',
    path: '/api/v1/game-data/clubs/$externalClubId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1GameDataClubsExternalClubIdMatchesRoute =
  ApiV1GameDataClubsExternalClubIdMatchesRouteImport.update({
    id: '/matches',
    path: '/matches',
    getParentRoute: () => ApiV1GameDataClubsExternalClubIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof AppOnboardingRoute
  '/player': typeof AppPlayerRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/openapi.yaml': typeof ApiV1OpenapiDotyamlRoute
  '/orgs/': typeof AppOrgsIndexRoute
  '/api/v1/identity/onboarding': typeof ApiV1IdentityOnboardingRoute
  '/api/v1/meta/ping': typeof ApiV1MetaPingRoute
  '/api/v1/organizations/mine': typeof ApiV1OrganizationsMineRoute
  '/api/v1/organizations/post-auth-destination': typeof ApiV1OrganizationsPostAuthDestinationRoute
  '/orgs/$orgId/': typeof AppOrgsOrgIdIndexRoute
  '/api/v1/organizations/': typeof ApiV1OrganizationsIndexRoute
  '/api/v1/game-data/clubs/$externalClubId': typeof ApiV1GameDataClubsExternalClubIdRouteWithChildren
  '/api/v1/game-data/clubs/search': typeof ApiV1GameDataClubsSearchRoute
  '/api/v1/organizations/$organizationId/invitations': typeof ApiV1OrganizationsOrganizationIdInvitationsRoute
  '/api/v1/organizations/invitations/accept': typeof ApiV1OrganizationsInvitationsAcceptRoute
  '/api/v1/game-data/clubs/$externalClubId/matches': typeof ApiV1GameDataClubsExternalClubIdMatchesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof AppOnboardingRoute
  '/player': typeof AppPlayerRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/openapi.yaml': typeof ApiV1OpenapiDotyamlRoute
  '/orgs': typeof AppOrgsIndexRoute
  '/api/v1/identity/onboarding': typeof ApiV1IdentityOnboardingRoute
  '/api/v1/meta/ping': typeof ApiV1MetaPingRoute
  '/api/v1/organizations/mine': typeof ApiV1OrganizationsMineRoute
  '/api/v1/organizations/post-auth-destination': typeof ApiV1OrganizationsPostAuthDestinationRoute
  '/orgs/$orgId': typeof AppOrgsOrgIdIndexRoute
  '/api/v1/organizations': typeof ApiV1OrganizationsIndexRoute
  '/api/v1/game-data/clubs/$externalClubId': typeof ApiV1GameDataClubsExternalClubIdRouteWithChildren
  '/api/v1/game-data/clubs/search': typeof ApiV1GameDataClubsSearchRoute
  '/api/v1/organizations/$organizationId/invitations': typeof ApiV1OrganizationsOrganizationIdInvitationsRoute
  '/api/v1/organizations/invitations/accept': typeof ApiV1OrganizationsInvitationsAcceptRoute
  '/api/v1/game-data/clubs/$externalClubId/matches': typeof ApiV1GameDataClubsExternalClubIdMatchesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/player': typeof AppPlayerRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/openapi.yaml': typeof ApiV1OpenapiDotyamlRoute
  '/_app/orgs/': typeof AppOrgsIndexRoute
  '/api/v1/identity/onboarding': typeof ApiV1IdentityOnboardingRoute
  '/api/v1/meta/ping': typeof ApiV1MetaPingRoute
  '/api/v1/organizations/mine': typeof ApiV1OrganizationsMineRoute
  '/api/v1/organizations/post-auth-destination': typeof ApiV1OrganizationsPostAuthDestinationRoute
  '/_app/orgs/$orgId/': typeof AppOrgsOrgIdIndexRoute
  '/api/v1/organizations/': typeof ApiV1OrganizationsIndexRoute
  '/api/v1/game-data/clubs/$externalClubId': typeof ApiV1GameDataClubsExternalClubIdRouteWithChildren
  '/api/v1/game-data/clubs/search': typeof ApiV1GameDataClubsSearchRoute
  '/api/v1/organizations/$organizationId/invitations': typeof ApiV1OrganizationsOrganizationIdInvitationsRoute
  '/api/v1/organizations/invitations/accept': typeof ApiV1OrganizationsInvitationsAcceptRoute
  '/api/v1/game-data/clubs/$externalClubId/matches': typeof ApiV1GameDataClubsExternalClubIdMatchesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/player'
    | '/login'
    | '/signup'
    | '/api/auth/$'
    | '/api/v1/openapi.json'
    | '/api/v1/openapi.yaml'
    | '/orgs/'
    | '/api/v1/identity/onboarding'
    | '/api/v1/meta/ping'
    | '/api/v1/organizations/mine'
    | '/api/v1/organizations/post-auth-destination'
    | '/orgs/$orgId/'
    | '/api/v1/organizations/'
    | '/api/v1/game-data/clubs/$externalClubId'
    | '/api/v1/game-data/clubs/search'
    | '/api/v1/organizations/$organizationId/invitations'
    | '/api/v1/organizations/invitations/accept'
    | '/api/v1/game-data/clubs/$externalClubId/matches'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/player'
    | '/login'
    | '/signup'
    | '/api/auth/$'
    | '/api/v1/openapi.json'
    | '/api/v1/openapi.yaml'
    | '/orgs'
    | '/api/v1/identity/onboarding'
    | '/api/v1/meta/ping'
    | '/api/v1/organizations/mine'
    | '/api/v1/organizations/post-auth-destination'
    | '/orgs/$orgId'
    | '/api/v1/organizations'
    | '/api/v1/game-data/clubs/$externalClubId'
    | '/api/v1/game-data/clubs/search'
    | '/api/v1/organizations/$organizationId/invitations'
    | '/api/v1/organizations/invitations/accept'
    | '/api/v1/game-data/clubs/$externalClubId/matches'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/onboarding'
    | '/_app/player'
    | '/_auth/login'
    | '/_auth/signup'
    | '/api/auth/$'
    | '/api/v1/openapi.json'
    | '/api/v1/openapi.yaml'
    | '/_app/orgs/'
    | '/api/v1/identity/onboarding'
    | '/api/v1/meta/ping'
    | '/api/v1/organizations/mine'
    | '/api/v1/organizations/post-auth-destination'
    | '/_app/orgs/$orgId/'
    | '/api/v1/organizations/'
    | '/api/v1/game-data/clubs/$externalClubId'
    | '/api/v1/game-data/clubs/search'
    | '/api/v1/organizations/$organizationId/invitations'
    | '/api/v1/organizations/invitations/accept'
    | '/api/v1/game-data/clubs/$externalClubId/matches'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1OpenapiDotjsonRoute: typeof ApiV1OpenapiDotjsonRoute
  ApiV1OpenapiDotyamlRoute: typeof ApiV1OpenapiDotyamlRoute
  ApiV1IdentityOnboardingRoute: typeof ApiV1IdentityOnboardingRoute
  ApiV1MetaPingRoute: typeof ApiV1MetaPingRoute
  ApiV1OrganizationsMineRoute: typeof ApiV1OrganizationsMineRoute
  ApiV1OrganizationsPostAuthDestinationRoute: typeof ApiV1OrganizationsPostAuthDestinationRoute
  ApiV1OrganizationsIndexRoute: typeof ApiV1OrganizationsIndexRoute
  ApiV1GameDataClubsExternalClubIdRoute: typeof ApiV1GameDataClubsExternalClubIdRouteWithChildren
  ApiV1GameDataClubsSearchRoute: typeof ApiV1GameDataClubsSearchRoute
  ApiV1OrganizationsOrganizationIdInvitationsRoute: typeof ApiV1OrganizationsOrganizationIdInvitationsRoute
  ApiV1OrganizationsInvitationsAcceptRoute: typeof ApiV1OrganizationsInvitationsAcceptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/player': {
      id: '/_app/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof AppPlayerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orgs/': {
      id: '/_app/orgs/'
      path: '/orgs'
      fullPath: '/orgs/'
      preLoaderRoute: typeof AppOrgsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/v1/openapi.yaml': {
      id: '/api/v1/openapi.yaml'
      path: '/api/v1/openapi.yaml'
      fullPath: '/api/v1/openapi.yaml'
      preLoaderRoute: typeof ApiV1OpenapiDotyamlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/openapi.json': {
      id: '/api/v1/openapi.json'
      path: '/api/v1/openapi.json'
      fullPath: '/api/v1/openapi.json'
      preLoaderRoute: typeof ApiV1OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/organizations/': {
      id: '/api/v1/organizations/'
      path: '/api/v1/organizations'
      fullPath: '/api/v1/organizations/'
      preLoaderRoute: typeof ApiV1OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/orgs/$orgId/': {
      id: '/_app/orgs/$orgId/'
      path: '/orgs/$orgId'
      fullPath: '/orgs/$orgId/'
      preLoaderRoute: typeof AppOrgsOrgIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/v1/organizations/post-auth-destination': {
      id: '/api/v1/organizations/post-auth-destination'
      path: '/api/v1/organizations/post-auth-destination'
      fullPath: '/api/v1/organizations/post-auth-destination'
      preLoaderRoute: typeof ApiV1OrganizationsPostAuthDestinationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/organizations/mine': {
      id: '/api/v1/organizations/mine'
      path: '/api/v1/organizations/mine'
      fullPath: '/api/v1/organizations/mine'
      preLoaderRoute: typeof ApiV1OrganizationsMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/meta/ping': {
      id: '/api/v1/meta/ping'
      path: '/api/v1/meta/ping'
      fullPath: '/api/v1/meta/ping'
      preLoaderRoute: typeof ApiV1MetaPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/identity/onboarding': {
      id: '/api/v1/identity/onboarding'
      path: '/api/v1/identity/onboarding'
      fullPath: '/api/v1/identity/onboarding'
      preLoaderRoute: typeof ApiV1IdentityOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/organizations/invitations/accept': {
      id: '/api/v1/organizations/invitations/accept'
      path: '/api/v1/organizations/invitations/accept'
      fullPath: '/api/v1/organizations/invitations/accept'
      preLoaderRoute: typeof ApiV1OrganizationsInvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/organizations/$organizationId/invitations': {
      id: '/api/v1/organizations/$organizationId/invitations'
      path: '/api/v1/organizations/$organizationId/invitations'
      fullPath: '/api/v1/organizations/$organizationId/invitations'
      preLoaderRoute: typeof ApiV1OrganizationsOrganizationIdInvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/game-data/clubs/search': {
      id: '/api/v1/game-data/clubs/search'
      path: '/api/v1/game-data/clubs/search'
      fullPath: '/api/v1/game-data/clubs/search'
      preLoaderRoute: typeof ApiV1GameDataClubsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/game-data/clubs/$externalClubId': {
      id: '/api/v1/game-data/clubs/$externalClubId'
      path: '/api/v1/game-data/clubs/$externalClubId'
      fullPath: '/api/v1/game-data/clubs/$externalClubId'
      preLoaderRoute: typeof ApiV1GameDataClubsExternalClubIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/game-data/clubs/$externalClubId/matches': {
      id: '/api/v1/game-data/clubs/$externalClubId/matches'
      path: '/matches'
      fullPath: '/api/v1/game-data/clubs/$externalClubId/matches'
      preLoaderRoute: typeof ApiV1GameDataClubsExternalClubIdMatchesRouteImport
      parentRoute: typeof ApiV1GameDataClubsExternalClubIdRoute
    }
  }
}

interface AppRouteChildren {
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPlayerRoute: typeof AppPlayerRoute
  AppOrgsIndexRoute: typeof AppOrgsIndexRoute
  AppOrgsOrgIdIndexRoute: typeof AppOrgsOrgIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppOnboardingRoute: AppOnboardingRoute,
  AppPlayerRoute: AppPlayerRoute,
  AppOrgsIndexRoute: AppOrgsIndexRoute,
  AppOrgsOrgIdIndexRoute: AppOrgsOrgIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ApiV1GameDataClubsExternalClubIdRouteChildren {
  ApiV1GameDataClubsExternalClubIdMatchesRoute: typeof ApiV1GameDataClubsExternalClubIdMatchesRoute
}

const ApiV1GameDataClubsExternalClubIdRouteChildren: ApiV1GameDataClubsExternalClubIdRouteChildren =
  {
    ApiV1GameDataClubsExternalClubIdMatchesRoute:
      ApiV1GameDataClubsExternalClubIdMatchesRoute,
  }

const ApiV1GameDataClubsExternalClubIdRouteWithChildren =
  ApiV1GameDataClubsExternalClubIdRoute._addFileChildren(
    ApiV1GameDataClubsExternalClubIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1OpenapiDotjsonRoute: ApiV1OpenapiDotjsonRoute,
  ApiV1OpenapiDotyamlRoute: ApiV1OpenapiDotyamlRoute,
  ApiV1IdentityOnboardingRoute: ApiV1IdentityOnboardingRoute,
  ApiV1MetaPingRoute: ApiV1MetaPingRoute,
  ApiV1OrganizationsMineRoute: ApiV1OrganizationsMineRoute,
  ApiV1OrganizationsPostAuthDestinationRoute:
    ApiV1OrganizationsPostAuthDestinationRoute,
  ApiV1OrganizationsIndexRoute: ApiV1OrganizationsIndexRoute,
  ApiV1GameDataClubsExternalClubIdRoute:
    ApiV1GameDataClubsExternalClubIdRouteWithChildren,
  ApiV1GameDataClubsSearchRoute: ApiV1GameDataClubsSearchRoute,
  ApiV1OrganizationsOrganizationIdInvitationsRoute:
    ApiV1OrganizationsOrganizationIdInvitationsRoute,
  ApiV1OrganizationsInvitationsAcceptRoute:
    ApiV1OrganizationsInvitationsAcceptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
