/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppPlayerRouteImport } from './routes/_app/player'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppOrgsIndexRouteImport } from './routes/_app/orgs/index'
import { Route as AppOnboardingIndexRouteImport } from './routes/_app/onboarding/index'
import { Route as ApiV1OpenapiDotyamlRouteImport } from './routes/api/v1/openapi[.]yaml'
import { Route as ApiV1OpenapiDotjsonRouteImport } from './routes/api/v1/openapi[.]json'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppRosterInvitationsAcceptRouteImport } from './routes/_app/roster-invitations/accept'
import { Route as AppPlayerGameAccountsRouteImport } from './routes/_app/player_.game-accounts'
import { Route as AppPlayerEaClubsRouteImport } from './routes/_app/player_.ea-clubs'
import { Route as AppPlayerCompetitionsRouteImport } from './routes/_app/player_.competitions'
import { Route as AppOrgsNewRouteImport } from './routes/_app/orgs/new'
import { Route as AppOnboardingTeamRouteImport } from './routes/_app/onboarding/team'
import { Route as AppOnboardingReviewRouteImport } from './routes/_app/onboarding/review'
import { Route as AppOnboardingOrganizationRouteImport } from './routes/_app/onboarding/organization'
import { Route as AppOnboardingInvitationRouteImport } from './routes/_app/onboarding/invitation'
import { Route as AppOnboardingIntentionRouteImport } from './routes/_app/onboarding/intention'
import { Route as AppOnboardingGameAccountRouteImport } from './routes/_app/onboarding/game-account'
import { Route as AppOnboardingGameRouteImport } from './routes/_app/onboarding/game'
import { Route as AppOnboardingCompetitionRouteImport } from './routes/_app/onboarding/competition'
import { Route as ApiV1OrganizationsIndexRouteImport } from './routes/api/v1/organizations/index'
import { Route as AppOrgsOrgIdIndexRouteImport } from './routes/_app/orgs/$orgId/index'
import { Route as AppInvitationsAcceptIndexRouteImport } from './routes/_app/invitations/accept/index'
import { Route as ApiV1RosterInvitationsAcceptRouteImport } from './routes/api/v1/roster-invitations/accept'
import { Route as ApiV1PlayersMeRouteImport } from './routes/api/v1/players/me'
import { Route as ApiV1OrganizationsPostAuthDestinationRouteImport } from './routes/api/v1/organizations/post-auth-destination'
import { Route as ApiV1OrganizationsNameAvailabilityRouteImport } from './routes/api/v1/organizations/name-availability'
import { Route as ApiV1OrganizationsMineRouteImport } from './routes/api/v1/organizations/mine'
import { Route as ApiV1MetaPingRouteImport } from './routes/api/v1/meta/ping'
import { Route as ApiV1IdentityOnboardingRouteImport } from './routes/api/v1/identity/onboarding'
import { Route as ApiV1CompetitionsMineRouteImport } from './routes/api/v1/competitions/mine'
import { Route as ApiV1AuthorizationEffectiveAccessRouteImport } from './routes/api/v1/authorization/effective-access'
import { Route as AppRosterInvitationsAcceptTokenRouteImport } from './routes/_app/roster-invitations/accept.$token'
import { Route as AppInvitationsAcceptPlainTokenRouteImport } from './routes/_app/invitations/accept/$plainToken'
import { Route as AppOrgsOrgIdCompetitionsIndexRouteImport } from './routes/_app/orgs/$orgId/competitions/index'
import { Route as ApiV1PlayersMeTeamsRouteImport } from './routes/api/v1/players/me/teams'
import { Route as ApiV1PlayersMeGameAccountsRouteImport } from './routes/api/v1/players/me/game-accounts'
import { Route as ApiV1PlayersMeActiveTeamRouteImport } from './routes/api/v1/players/me/active-team'
import { Route as ApiV1OrganizationsInvitationsAcceptRouteImport } from './routes/api/v1/organizations/invitations.accept'
import { Route as ApiV1OrganizationsOrganizationIdTeamsRouteImport } from './routes/api/v1/organizations/$organizationId/teams'
import { Route as ApiV1OrganizationsOrganizationIdInvitationsRouteImport } from './routes/api/v1/organizations/$organizationId.invitations'
import { Route as ApiV1OrganizationsOrganizationIdCompetitionsRouteImport } from './routes/api/v1/organizations/$organizationId/competitions'
import { Route as ApiV1IdentityOnboardingPlayerRouteImport } from './routes/api/v1/identity/onboarding/player'
import { Route as ApiV1IdentityOnboardingOrganizationRouteImport } from './routes/api/v1/identity/onboarding/organization'
import { Route as ApiV1IdentityOnboardingInvitationRouteImport } from './routes/api/v1/identity/onboarding/invitation'
import { Route as ApiV1GameDataClubsSearchRouteImport } from './routes/api/v1/game-data/clubs/search'
import { Route as ApiV1GameDataClubsExternalClubIdRouteImport } from './routes/api/v1/game-data/clubs/$externalClubId'
import { Route as ApiV1CompetitionsInvitationsAcceptRouteImport } from './routes/api/v1/competitions/invitations.accept'
import { Route as AppOrgsOrgIdCompetitionsNewRouteImport } from './routes/_app/orgs/$orgId/competitions/new'
import { Route as AppOrgsOrgIdCompetitionsCompetitionIdIndexRouteImport } from './routes/_app/orgs/$orgId/competitions/$competitionId/index'
import { Route as ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRouteImport } from './routes/api/v1/organizations/$organizationId/competitions/$competitionId'
import { Route as ApiV1GameDataClubsExternalClubIdMatchesRouteImport } from './routes/api/v1/game-data/clubs/$externalClubId.matches'
import { Route as AppOrgsOrgIdCompetitionsCompetitionIdTeamsRouteImport } from './routes/_app/orgs/$orgId/competitions/$competitionId/teams'
import { Route as AppOrgsOrgIdCompetitionsCompetitionIdSetupRouteImport } from './routes/_app/orgs/$orgId/competitions/$competitionId/setup'
import { Route as ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamManagementRouteImport } from './routes/api/v1/organizations/$organizationId/competitions/$competitionId/team-management'
import { Route as ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdPublishRouteImport } from './routes/api/v1/organizations/$organizationId/competitions/$competitionId/publish'
import { Route as ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdParticipantsRouteImport } from './routes/api/v1/organizations/$organizationId/competitions/$competitionId/participants'
import { Route as ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdInvitationsRouteImport } from './routes/api/v1/organizations/$organizationId/competitions/$competitionId/invitations'
import { Route as ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamManagementTeamIdRouteImport } from './routes/api/v1/organizations/$organizationId/competitions/$competitionId/team-management/$teamId'
import { Route as ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdParticipantsEntryIdRouteImport } from './routes/api/v1/organizations/$organizationId/competitions/$competitionId/participants/$entryId'
import { Route as ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterInvitationsRouteImport } from './routes/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster-invitations'
import { Route as ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdExternalClubRouteImport } from './routes/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/external-club'
import { Route as ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdEntriesEntryIdDecisionRouteImport } from './routes/api/v1/organizations/$organizationId/competitions/$competitionId/entries/$entryId/$decision'
import { Route as ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterOpenRouteImport } from './routes/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster/open'
import { Route as ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterCloseRouteImport } from './routes/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster/close'
import { Route as ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterMembershipIdRouteImport } from './routes/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster/$membershipId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppPlayerRoute = AppPlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgsIndexRoute = AppOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingIndexRoute = AppOnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOnboardingRoute,
} as any)
const ApiV1OpenapiDotyamlRoute = ApiV1OpenapiDotyamlRouteImport.update({
  id: '/api/v1/openapi.yaml',
  path: '/api/v1/openapi.yaml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OpenapiDotjsonRoute = ApiV1OpenapiDotjsonRouteImport.update({
  id: '/api/v1/openapi.json',
  path: '/api/v1/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRosterInvitationsAcceptRoute =
  AppRosterInvitationsAcceptRouteImport.update({
    id: '/roster-invitations/accept',
    path: '/roster-invitations/accept',
    getParentRoute: () => AppRoute,
  } as any)
const AppPlayerGameAccountsRoute = AppPlayerGameAccountsRouteImport.update({
  id: '/player_/game-accounts',
  path: '/player/game-accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayerEaClubsRoute = AppPlayerEaClubsRouteImport.update({
  id: '/player_/ea-clubs',
  path: '/player/ea-clubs',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayerCompetitionsRoute = AppPlayerCompetitionsRouteImport.update({
  id: '/player_/competitions',
  path: '/player/competitions',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgsNewRoute = AppOrgsNewRouteImport.update({
  id: '/orgs/new',
  path: '/orgs/new',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingTeamRoute = AppOnboardingTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppOnboardingRoute,
} as any)
const AppOnboardingReviewRoute = AppOnboardingReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppOnboardingRoute,
} as any)
const AppOnboardingOrganizationRoute =
  AppOnboardingOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => AppOnboardingRoute,
  } as any)
const AppOnboardingInvitationRoute = AppOnboardingInvitationRouteImport.update({
  id: '/invitation',
  path: '/invitation',
  getParentRoute: () => AppOnboardingRoute,
} as any)
const AppOnboardingIntentionRoute = AppOnboardingIntentionRouteImport.update({
  id: '/intention',
  path: '/intention',
  getParentRoute: () => AppOnboardingRoute,
} as any)
const AppOnboardingGameAccountRoute =
  AppOnboardingGameAccountRouteImport.update({
    id: '/game-account',
    path: '/game-account',
    getParentRoute: () => AppOnboardingRoute,
  } as any)
const AppOnboardingGameRoute = AppOnboardingGameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => AppOnboardingRoute,
} as any)
const AppOnboardingCompetitionRoute =
  AppOnboardingCompetitionRouteImport.update({
    id: '/competition',
    path: '/competition',
    getParentRoute: () => AppOnboardingRoute,
  } as any)
const ApiV1OrganizationsIndexRoute = ApiV1OrganizationsIndexRouteImport.update({
  id: '/api/v1/organizations/',
  path: '/api/v1/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrgsOrgIdIndexRoute = AppOrgsOrgIdIndexRouteImport.update({
  id: '/orgs/$orgId/',
  path: '/orgs/$orgId/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvitationsAcceptIndexRoute =
  AppInvitationsAcceptIndexRouteImport.update({
    id: '/invitations/accept/',
    path: '/invitations/accept/',
    getParentRoute: () => AppRoute,
  } as any)
const ApiV1RosterInvitationsAcceptRoute =
  ApiV1RosterInvitationsAcceptRouteImport.update({
    id: '/api/v1/roster-invitations/accept',
    path: '/api/v1/roster-invitations/accept',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1PlayersMeRoute = ApiV1PlayersMeRouteImport.update({
  id: '/api/v1/players/me',
  path: '/api/v1/players/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OrganizationsPostAuthDestinationRoute =
  ApiV1OrganizationsPostAuthDestinationRouteImport.update({
    id: '/api/v1/organizations/post-auth-destination',
    path: '/api/v1/organizations/post-auth-destination',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1OrganizationsNameAvailabilityRoute =
  ApiV1OrganizationsNameAvailabilityRouteImport.update({
    id: '/api/v1/organizations/name-availability',
    path: '/api/v1/organizations/name-availability',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1OrganizationsMineRoute = ApiV1OrganizationsMineRouteImport.update({
  id: '/api/v1/organizations/mine',
  path: '/api/v1/organizations/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MetaPingRoute = ApiV1MetaPingRouteImport.update({
  id: '/api/v1/meta/ping',
  path: '/api/v1/meta/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1IdentityOnboardingRoute = ApiV1IdentityOnboardingRouteImport.update({
  id: '/api/v1/identity/onboarding',
  path: '/api/v1/identity/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CompetitionsMineRoute = ApiV1CompetitionsMineRouteImport.update({
  id: '/api/v1/competitions/mine',
  path: '/api/v1/competitions/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthorizationEffectiveAccessRoute =
  ApiV1AuthorizationEffectiveAccessRouteImport.update({
    id: '/api/v1/authorization/effective-access',
    path: '/api/v1/authorization/effective-access',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppRosterInvitationsAcceptTokenRoute =
  AppRosterInvitationsAcceptTokenRouteImport.update({
    id: '/$token',
    path: '/$token',
    getParentRoute: () => AppRosterInvitationsAcceptRoute,
  } as any)
const AppInvitationsAcceptPlainTokenRoute =
  AppInvitationsAcceptPlainTokenRouteImport.update({
    id: '/invitations/accept/$plainToken',
    path: '/invitations/accept/$plainToken',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrgsOrgIdCompetitionsIndexRoute =
  AppOrgsOrgIdCompetitionsIndexRouteImport.update({
    id: '/orgs/$orgId/competitions/',
    path: '/orgs/$orgId/competitions/',
    getParentRoute: () => AppRoute,
  } as any)
const ApiV1PlayersMeTeamsRoute = ApiV1PlayersMeTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => ApiV1PlayersMeRoute,
} as any)
const ApiV1PlayersMeGameAccountsRoute =
  ApiV1PlayersMeGameAccountsRouteImport.update({
    id: '/game-accounts',
    path: '/game-accounts',
    getParentRoute: () => ApiV1PlayersMeRoute,
  } as any)
const ApiV1PlayersMeActiveTeamRoute =
  ApiV1PlayersMeActiveTeamRouteImport.update({
    id: '/active-team',
    path: '/active-team',
    getParentRoute: () => ApiV1PlayersMeRoute,
  } as any)
const ApiV1OrganizationsInvitationsAcceptRoute =
  ApiV1OrganizationsInvitationsAcceptRouteImport.update({
    id: '/api/v1/organizations/invitations/accept',
    path: '/api/v1/organizations/invitations/accept',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1OrganizationsOrganizationIdTeamsRoute =
  ApiV1OrganizationsOrganizationIdTeamsRouteImport.update({
    id: '/api/v1/organizations/$organizationId/teams',
    path: '/api/v1/organizations/$organizationId/teams',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1OrganizationsOrganizationIdInvitationsRoute =
  ApiV1OrganizationsOrganizationIdInvitationsRouteImport.update({
    id: '/api/v1/organizations/$organizationId/invitations',
    path: '/api/v1/organizations/$organizationId/invitations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1OrganizationsOrganizationIdCompetitionsRoute =
  ApiV1OrganizationsOrganizationIdCompetitionsRouteImport.update({
    id: '/api/v1/organizations/$organizationId/competitions',
    path: '/api/v1/organizations/$organizationId/competitions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1IdentityOnboardingPlayerRoute =
  ApiV1IdentityOnboardingPlayerRouteImport.update({
    id: '/player',
    path: '/player',
    getParentRoute: () => ApiV1IdentityOnboardingRoute,
  } as any)
const ApiV1IdentityOnboardingOrganizationRoute =
  ApiV1IdentityOnboardingOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => ApiV1IdentityOnboardingRoute,
  } as any)
const ApiV1IdentityOnboardingInvitationRoute =
  ApiV1IdentityOnboardingInvitationRouteImport.update({
    id: '/invitation',
    path: '/invitation',
    getParentRoute: () => ApiV1IdentityOnboardingRoute,
  } as any)
const ApiV1GameDataClubsSearchRoute =
  ApiV1GameDataClubsSearchRouteImport.update({
    id: '/api/v1/game-data/clubs/search',
    path: '/api/v1/game-data/clubs/search',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1GameDataClubsExternalClubIdRoute =
  ApiV1GameDataClubsExternalClubIdRouteImport.update({
    id: '/api/v1/game-data/clubs/$externalClubId',
    path: '/api/v1/game-data/clubs/$externalClubId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1CompetitionsInvitationsAcceptRoute =
  ApiV1CompetitionsInvitationsAcceptRouteImport.update({
    id: '/api/v1/competitions/invitations/accept',
    path: '/api/v1/competitions/invitations/accept',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppOrgsOrgIdCompetitionsNewRoute =
  AppOrgsOrgIdCompetitionsNewRouteImport.update({
    id: '/orgs/$orgId/competitions/new',
    path: '/orgs/$orgId/competitions/new',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrgsOrgIdCompetitionsCompetitionIdIndexRoute =
  AppOrgsOrgIdCompetitionsCompetitionIdIndexRouteImport.update({
    id: '/orgs/$orgId/competitions/$competitionId/',
    path: '/orgs/$orgId/competitions/$competitionId/',
    getParentRoute: () => AppRoute,
  } as any)
const ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRoute =
  ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRouteImport.update({
    id: '/$competitionId',
    path: '/$competitionId',
    getParentRoute: () => ApiV1OrganizationsOrganizationIdCompetitionsRoute,
  } as any)
const ApiV1GameDataClubsExternalClubIdMatchesRoute =
  ApiV1GameDataClubsExternalClubIdMatchesRouteImport.update({
    id: '/matches',
    path: '/matches',
    getParentRoute: () => ApiV1GameDataClubsExternalClubIdRoute,
  } as any)
const AppOrgsOrgIdCompetitionsCompetitionIdTeamsRoute =
  AppOrgsOrgIdCompetitionsCompetitionIdTeamsRouteImport.update({
    id: '/orgs/$orgId/competitions/$competitionId/teams',
    path: '/orgs/$orgId/competitions/$competitionId/teams',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrgsOrgIdCompetitionsCompetitionIdSetupRoute =
  AppOrgsOrgIdCompetitionsCompetitionIdSetupRouteImport.update({
    id: '/orgs/$orgId/competitions/$competitionId/setup',
    path: '/orgs/$orgId/competitions/$competitionId/setup',
    getParentRoute: () => AppRoute,
  } as any)
const ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamManagementRoute =
  ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamManagementRouteImport.update(
    {
      id: '/team-management',
      path: '/team-management',
      getParentRoute: () =>
        ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRoute,
    } as any,
  )
const ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdPublishRoute =
  ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdPublishRouteImport.update(
    {
      id: '/publish',
      path: '/publish',
      getParentRoute: () =>
        ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRoute,
    } as any,
  )
const ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdParticipantsRoute =
  ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdParticipantsRouteImport.update(
    {
      id: '/participants',
      path: '/participants',
      getParentRoute: () =>
        ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRoute,
    } as any,
  )
const ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdInvitationsRoute =
  ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdInvitationsRouteImport.update(
    {
      id: '/invitations',
      path: '/invitations',
      getParentRoute: () =>
        ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRoute,
    } as any,
  )
const ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamManagementTeamIdRoute =
  ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamManagementTeamIdRouteImport.update(
    {
      id: '/$teamId',
      path: '/$teamId',
      getParentRoute: () =>
        ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamManagementRoute,
    } as any,
  )
const ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdParticipantsEntryIdRoute =
  ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdParticipantsEntryIdRouteImport.update(
    {
      id: '/$entryId',
      path: '/$entryId',
      getParentRoute: () =>
        ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdParticipantsRoute,
    } as any,
  )
const ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterInvitationsRoute =
  ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterInvitationsRouteImport.update(
    {
      id: '/teams/$teamId/roster-invitations',
      path: '/teams/$teamId/roster-invitations',
      getParentRoute: () =>
        ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRoute,
    } as any,
  )
const ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdExternalClubRoute =
  ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdExternalClubRouteImport.update(
    {
      id: '/teams/$teamId/external-club',
      path: '/teams/$teamId/external-club',
      getParentRoute: () =>
        ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRoute,
    } as any,
  )
const ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdEntriesEntryIdDecisionRoute =
  ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdEntriesEntryIdDecisionRouteImport.update(
    {
      id: '/entries/$entryId/$decision',
      path: '/entries/$entryId/$decision',
      getParentRoute: () =>
        ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRoute,
    } as any,
  )
const ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterOpenRoute =
  ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterOpenRouteImport.update(
    {
      id: '/teams/$teamId/roster/open',
      path: '/teams/$teamId/roster/open',
      getParentRoute: () =>
        ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRoute,
    } as any,
  )
const ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterCloseRoute =
  ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterCloseRouteImport.update(
    {
      id: '/teams/$teamId/roster/close',
      path: '/teams/$teamId/roster/close',
      getParentRoute: () =>
        ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRoute,
    } as any,
  )
const ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterMembershipIdRoute =
  ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterMembershipIdRouteImport.update(
    {
      id: '/teams/$teamId/roster/$membershipId',
      path: '/teams/$teamId/roster/$membershipId',
      getParentRoute: () =>
        ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof AppOnboardingRouteWithChildren
  '/player': typeof AppPlayerRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/onboarding/competition': typeof AppOnboardingCompetitionRoute
  '/onboarding/game': typeof AppOnboardingGameRoute
  '/onboarding/game-account': typeof AppOnboardingGameAccountRoute
  '/onboarding/intention': typeof AppOnboardingIntentionRoute
  '/onboarding/invitation': typeof AppOnboardingInvitationRoute
  '/onboarding/organization': typeof AppOnboardingOrganizationRoute
  '/onboarding/review': typeof AppOnboardingReviewRoute
  '/onboarding/team': typeof AppOnboardingTeamRoute
  '/orgs/new': typeof AppOrgsNewRoute
  '/player/competitions': typeof AppPlayerCompetitionsRoute
  '/player/ea-clubs': typeof AppPlayerEaClubsRoute
  '/player/game-accounts': typeof AppPlayerGameAccountsRoute
  '/roster-invitations/accept': typeof AppRosterInvitationsAcceptRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/openapi.yaml': typeof ApiV1OpenapiDotyamlRoute
  '/onboarding/': typeof AppOnboardingIndexRoute
  '/orgs/': typeof AppOrgsIndexRoute
  '/invitations/accept/$plainToken': typeof AppInvitationsAcceptPlainTokenRoute
  '/roster-invitations/accept/$token': typeof AppRosterInvitationsAcceptTokenRoute
  '/api/v1/authorization/effective-access': typeof ApiV1AuthorizationEffectiveAccessRoute
  '/api/v1/competitions/mine': typeof ApiV1CompetitionsMineRoute
  '/api/v1/identity/onboarding': typeof ApiV1IdentityOnboardingRouteWithChildren
  '/api/v1/meta/ping': typeof ApiV1MetaPingRoute
  '/api/v1/organizations/mine': typeof ApiV1OrganizationsMineRoute
  '/api/v1/organizations/name-availability': typeof ApiV1OrganizationsNameAvailabilityRoute
  '/api/v1/organizations/post-auth-destination': typeof ApiV1OrganizationsPostAuthDestinationRoute
  '/api/v1/players/me': typeof ApiV1PlayersMeRouteWithChildren
  '/api/v1/roster-invitations/accept': typeof ApiV1RosterInvitationsAcceptRoute
  '/invitations/accept/': typeof AppInvitationsAcceptIndexRoute
  '/orgs/$orgId/': typeof AppOrgsOrgIdIndexRoute
  '/api/v1/organizations/': typeof ApiV1OrganizationsIndexRoute
  '/orgs/$orgId/competitions/new': typeof AppOrgsOrgIdCompetitionsNewRoute
  '/api/v1/competitions/invitations/accept': typeof ApiV1CompetitionsInvitationsAcceptRoute
  '/api/v1/game-data/clubs/$externalClubId': typeof ApiV1GameDataClubsExternalClubIdRouteWithChildren
  '/api/v1/game-data/clubs/search': typeof ApiV1GameDataClubsSearchRoute
  '/api/v1/identity/onboarding/invitation': typeof ApiV1IdentityOnboardingInvitationRoute
  '/api/v1/identity/onboarding/organization': typeof ApiV1IdentityOnboardingOrganizationRoute
  '/api/v1/identity/onboarding/player': typeof ApiV1IdentityOnboardingPlayerRoute
  '/api/v1/organizations/$organizationId/competitions': typeof ApiV1OrganizationsOrganizationIdCompetitionsRouteWithChildren
  '/api/v1/organizations/$organizationId/invitations': typeof ApiV1OrganizationsOrganizationIdInvitationsRoute
  '/api/v1/organizations/$organizationId/teams': typeof ApiV1OrganizationsOrganizationIdTeamsRoute
  '/api/v1/organizations/invitations/accept': typeof ApiV1OrganizationsInvitationsAcceptRoute
  '/api/v1/players/me/active-team': typeof ApiV1PlayersMeActiveTeamRoute
  '/api/v1/players/me/game-accounts': typeof ApiV1PlayersMeGameAccountsRoute
  '/api/v1/players/me/teams': typeof ApiV1PlayersMeTeamsRoute
  '/orgs/$orgId/competitions/': typeof AppOrgsOrgIdCompetitionsIndexRoute
  '/orgs/$orgId/competitions/$competitionId/setup': typeof AppOrgsOrgIdCompetitionsCompetitionIdSetupRoute
  '/orgs/$orgId/competitions/$competitionId/teams': typeof AppOrgsOrgIdCompetitionsCompetitionIdTeamsRoute
  '/api/v1/game-data/clubs/$externalClubId/matches': typeof ApiV1GameDataClubsExternalClubIdMatchesRoute
  '/api/v1/organizations/$organizationId/competitions/$competitionId': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRouteWithChildren
  '/orgs/$orgId/competitions/$competitionId/': typeof AppOrgsOrgIdCompetitionsCompetitionIdIndexRoute
  '/api/v1/organizations/$organizationId/competitions/$competitionId/invitations': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdInvitationsRoute
  '/api/v1/organizations/$organizationId/competitions/$competitionId/participants': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdParticipantsRouteWithChildren
  '/api/v1/organizations/$organizationId/competitions/$competitionId/publish': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdPublishRoute
  '/api/v1/organizations/$organizationId/competitions/$competitionId/team-management': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamManagementRouteWithChildren
  '/api/v1/organizations/$organizationId/competitions/$competitionId/participants/$entryId': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdParticipantsEntryIdRoute
  '/api/v1/organizations/$organizationId/competitions/$competitionId/team-management/$teamId': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamManagementTeamIdRoute
  '/api/v1/organizations/$organizationId/competitions/$competitionId/entries/$entryId/$decision': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdEntriesEntryIdDecisionRoute
  '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/external-club': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdExternalClubRoute
  '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster-invitations': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterInvitationsRoute
  '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster/$membershipId': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterMembershipIdRoute
  '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster/close': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterCloseRoute
  '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster/open': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterOpenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/player': typeof AppPlayerRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/onboarding/competition': typeof AppOnboardingCompetitionRoute
  '/onboarding/game': typeof AppOnboardingGameRoute
  '/onboarding/game-account': typeof AppOnboardingGameAccountRoute
  '/onboarding/intention': typeof AppOnboardingIntentionRoute
  '/onboarding/invitation': typeof AppOnboardingInvitationRoute
  '/onboarding/organization': typeof AppOnboardingOrganizationRoute
  '/onboarding/review': typeof AppOnboardingReviewRoute
  '/onboarding/team': typeof AppOnboardingTeamRoute
  '/orgs/new': typeof AppOrgsNewRoute
  '/player/competitions': typeof AppPlayerCompetitionsRoute
  '/player/ea-clubs': typeof AppPlayerEaClubsRoute
  '/player/game-accounts': typeof AppPlayerGameAccountsRoute
  '/roster-invitations/accept': typeof AppRosterInvitationsAcceptRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/openapi.yaml': typeof ApiV1OpenapiDotyamlRoute
  '/onboarding': typeof AppOnboardingIndexRoute
  '/orgs': typeof AppOrgsIndexRoute
  '/invitations/accept/$plainToken': typeof AppInvitationsAcceptPlainTokenRoute
  '/roster-invitations/accept/$token': typeof AppRosterInvitationsAcceptTokenRoute
  '/api/v1/authorization/effective-access': typeof ApiV1AuthorizationEffectiveAccessRoute
  '/api/v1/competitions/mine': typeof ApiV1CompetitionsMineRoute
  '/api/v1/identity/onboarding': typeof ApiV1IdentityOnboardingRouteWithChildren
  '/api/v1/meta/ping': typeof ApiV1MetaPingRoute
  '/api/v1/organizations/mine': typeof ApiV1OrganizationsMineRoute
  '/api/v1/organizations/name-availability': typeof ApiV1OrganizationsNameAvailabilityRoute
  '/api/v1/organizations/post-auth-destination': typeof ApiV1OrganizationsPostAuthDestinationRoute
  '/api/v1/players/me': typeof ApiV1PlayersMeRouteWithChildren
  '/api/v1/roster-invitations/accept': typeof ApiV1RosterInvitationsAcceptRoute
  '/invitations/accept': typeof AppInvitationsAcceptIndexRoute
  '/orgs/$orgId': typeof AppOrgsOrgIdIndexRoute
  '/api/v1/organizations': typeof ApiV1OrganizationsIndexRoute
  '/orgs/$orgId/competitions/new': typeof AppOrgsOrgIdCompetitionsNewRoute
  '/api/v1/competitions/invitations/accept': typeof ApiV1CompetitionsInvitationsAcceptRoute
  '/api/v1/game-data/clubs/$externalClubId': typeof ApiV1GameDataClubsExternalClubIdRouteWithChildren
  '/api/v1/game-data/clubs/search': typeof ApiV1GameDataClubsSearchRoute
  '/api/v1/identity/onboarding/invitation': typeof ApiV1IdentityOnboardingInvitationRoute
  '/api/v1/identity/onboarding/organization': typeof ApiV1IdentityOnboardingOrganizationRoute
  '/api/v1/identity/onboarding/player': typeof ApiV1IdentityOnboardingPlayerRoute
  '/api/v1/organizations/$organizationId/competitions': typeof ApiV1OrganizationsOrganizationIdCompetitionsRouteWithChildren
  '/api/v1/organizations/$organizationId/invitations': typeof ApiV1OrganizationsOrganizationIdInvitationsRoute
  '/api/v1/organizations/$organizationId/teams': typeof ApiV1OrganizationsOrganizationIdTeamsRoute
  '/api/v1/organizations/invitations/accept': typeof ApiV1OrganizationsInvitationsAcceptRoute
  '/api/v1/players/me/active-team': typeof ApiV1PlayersMeActiveTeamRoute
  '/api/v1/players/me/game-accounts': typeof ApiV1PlayersMeGameAccountsRoute
  '/api/v1/players/me/teams': typeof ApiV1PlayersMeTeamsRoute
  '/orgs/$orgId/competitions': typeof AppOrgsOrgIdCompetitionsIndexRoute
  '/orgs/$orgId/competitions/$competitionId/setup': typeof AppOrgsOrgIdCompetitionsCompetitionIdSetupRoute
  '/orgs/$orgId/competitions/$competitionId/teams': typeof AppOrgsOrgIdCompetitionsCompetitionIdTeamsRoute
  '/api/v1/game-data/clubs/$externalClubId/matches': typeof ApiV1GameDataClubsExternalClubIdMatchesRoute
  '/api/v1/organizations/$organizationId/competitions/$competitionId': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRouteWithChildren
  '/orgs/$orgId/competitions/$competitionId': typeof AppOrgsOrgIdCompetitionsCompetitionIdIndexRoute
  '/api/v1/organizations/$organizationId/competitions/$competitionId/invitations': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdInvitationsRoute
  '/api/v1/organizations/$organizationId/competitions/$competitionId/participants': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdParticipantsRouteWithChildren
  '/api/v1/organizations/$organizationId/competitions/$competitionId/publish': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdPublishRoute
  '/api/v1/organizations/$organizationId/competitions/$competitionId/team-management': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamManagementRouteWithChildren
  '/api/v1/organizations/$organizationId/competitions/$competitionId/participants/$entryId': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdParticipantsEntryIdRoute
  '/api/v1/organizations/$organizationId/competitions/$competitionId/team-management/$teamId': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamManagementTeamIdRoute
  '/api/v1/organizations/$organizationId/competitions/$competitionId/entries/$entryId/$decision': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdEntriesEntryIdDecisionRoute
  '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/external-club': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdExternalClubRoute
  '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster-invitations': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterInvitationsRoute
  '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster/$membershipId': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterMembershipIdRoute
  '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster/close': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterCloseRoute
  '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster/open': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterOpenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/onboarding': typeof AppOnboardingRouteWithChildren
  '/_app/player': typeof AppPlayerRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_app/onboarding/competition': typeof AppOnboardingCompetitionRoute
  '/_app/onboarding/game': typeof AppOnboardingGameRoute
  '/_app/onboarding/game-account': typeof AppOnboardingGameAccountRoute
  '/_app/onboarding/intention': typeof AppOnboardingIntentionRoute
  '/_app/onboarding/invitation': typeof AppOnboardingInvitationRoute
  '/_app/onboarding/organization': typeof AppOnboardingOrganizationRoute
  '/_app/onboarding/review': typeof AppOnboardingReviewRoute
  '/_app/onboarding/team': typeof AppOnboardingTeamRoute
  '/_app/orgs/new': typeof AppOrgsNewRoute
  '/_app/player_/competitions': typeof AppPlayerCompetitionsRoute
  '/_app/player_/ea-clubs': typeof AppPlayerEaClubsRoute
  '/_app/player_/game-accounts': typeof AppPlayerGameAccountsRoute
  '/_app/roster-invitations/accept': typeof AppRosterInvitationsAcceptRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/openapi.yaml': typeof ApiV1OpenapiDotyamlRoute
  '/_app/onboarding/': typeof AppOnboardingIndexRoute
  '/_app/orgs/': typeof AppOrgsIndexRoute
  '/_app/invitations/accept/$plainToken': typeof AppInvitationsAcceptPlainTokenRoute
  '/_app/roster-invitations/accept/$token': typeof AppRosterInvitationsAcceptTokenRoute
  '/api/v1/authorization/effective-access': typeof ApiV1AuthorizationEffectiveAccessRoute
  '/api/v1/competitions/mine': typeof ApiV1CompetitionsMineRoute
  '/api/v1/identity/onboarding': typeof ApiV1IdentityOnboardingRouteWithChildren
  '/api/v1/meta/ping': typeof ApiV1MetaPingRoute
  '/api/v1/organizations/mine': typeof ApiV1OrganizationsMineRoute
  '/api/v1/organizations/name-availability': typeof ApiV1OrganizationsNameAvailabilityRoute
  '/api/v1/organizations/post-auth-destination': typeof ApiV1OrganizationsPostAuthDestinationRoute
  '/api/v1/players/me': typeof ApiV1PlayersMeRouteWithChildren
  '/api/v1/roster-invitations/accept': typeof ApiV1RosterInvitationsAcceptRoute
  '/_app/invitations/accept/': typeof AppInvitationsAcceptIndexRoute
  '/_app/orgs/$orgId/': typeof AppOrgsOrgIdIndexRoute
  '/api/v1/organizations/': typeof ApiV1OrganizationsIndexRoute
  '/_app/orgs/$orgId/competitions/new': typeof AppOrgsOrgIdCompetitionsNewRoute
  '/api/v1/competitions/invitations/accept': typeof ApiV1CompetitionsInvitationsAcceptRoute
  '/api/v1/game-data/clubs/$externalClubId': typeof ApiV1GameDataClubsExternalClubIdRouteWithChildren
  '/api/v1/game-data/clubs/search': typeof ApiV1GameDataClubsSearchRoute
  '/api/v1/identity/onboarding/invitation': typeof ApiV1IdentityOnboardingInvitationRoute
  '/api/v1/identity/onboarding/organization': typeof ApiV1IdentityOnboardingOrganizationRoute
  '/api/v1/identity/onboarding/player': typeof ApiV1IdentityOnboardingPlayerRoute
  '/api/v1/organizations/$organizationId/competitions': typeof ApiV1OrganizationsOrganizationIdCompetitionsRouteWithChildren
  '/api/v1/organizations/$organizationId/invitations': typeof ApiV1OrganizationsOrganizationIdInvitationsRoute
  '/api/v1/organizations/$organizationId/teams': typeof ApiV1OrganizationsOrganizationIdTeamsRoute
  '/api/v1/organizations/invitations/accept': typeof ApiV1OrganizationsInvitationsAcceptRoute
  '/api/v1/players/me/active-team': typeof ApiV1PlayersMeActiveTeamRoute
  '/api/v1/players/me/game-accounts': typeof ApiV1PlayersMeGameAccountsRoute
  '/api/v1/players/me/teams': typeof ApiV1PlayersMeTeamsRoute
  '/_app/orgs/$orgId/competitions/': typeof AppOrgsOrgIdCompetitionsIndexRoute
  '/_app/orgs/$orgId/competitions/$competitionId/setup': typeof AppOrgsOrgIdCompetitionsCompetitionIdSetupRoute
  '/_app/orgs/$orgId/competitions/$competitionId/teams': typeof AppOrgsOrgIdCompetitionsCompetitionIdTeamsRoute
  '/api/v1/game-data/clubs/$externalClubId/matches': typeof ApiV1GameDataClubsExternalClubIdMatchesRoute
  '/api/v1/organizations/$organizationId/competitions/$competitionId': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRouteWithChildren
  '/_app/orgs/$orgId/competitions/$competitionId/': typeof AppOrgsOrgIdCompetitionsCompetitionIdIndexRoute
  '/api/v1/organizations/$organizationId/competitions/$competitionId/invitations': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdInvitationsRoute
  '/api/v1/organizations/$organizationId/competitions/$competitionId/participants': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdParticipantsRouteWithChildren
  '/api/v1/organizations/$organizationId/competitions/$competitionId/publish': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdPublishRoute
  '/api/v1/organizations/$organizationId/competitions/$competitionId/team-management': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamManagementRouteWithChildren
  '/api/v1/organizations/$organizationId/competitions/$competitionId/participants/$entryId': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdParticipantsEntryIdRoute
  '/api/v1/organizations/$organizationId/competitions/$competitionId/team-management/$teamId': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamManagementTeamIdRoute
  '/api/v1/organizations/$organizationId/competitions/$competitionId/entries/$entryId/$decision': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdEntriesEntryIdDecisionRoute
  '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/external-club': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdExternalClubRoute
  '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster-invitations': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterInvitationsRoute
  '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster/$membershipId': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterMembershipIdRoute
  '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster/close': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterCloseRoute
  '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster/open': typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterOpenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/player'
    | '/login'
    | '/signup'
    | '/onboarding/competition'
    | '/onboarding/game'
    | '/onboarding/game-account'
    | '/onboarding/intention'
    | '/onboarding/invitation'
    | '/onboarding/organization'
    | '/onboarding/review'
    | '/onboarding/team'
    | '/orgs/new'
    | '/player/competitions'
    | '/player/ea-clubs'
    | '/player/game-accounts'
    | '/roster-invitations/accept'
    | '/api/auth/$'
    | '/api/v1/openapi.json'
    | '/api/v1/openapi.yaml'
    | '/onboarding/'
    | '/orgs/'
    | '/invitations/accept/$plainToken'
    | '/roster-invitations/accept/$token'
    | '/api/v1/authorization/effective-access'
    | '/api/v1/competitions/mine'
    | '/api/v1/identity/onboarding'
    | '/api/v1/meta/ping'
    | '/api/v1/organizations/mine'
    | '/api/v1/organizations/name-availability'
    | '/api/v1/organizations/post-auth-destination'
    | '/api/v1/players/me'
    | '/api/v1/roster-invitations/accept'
    | '/invitations/accept/'
    | '/orgs/$orgId/'
    | '/api/v1/organizations/'
    | '/orgs/$orgId/competitions/new'
    | '/api/v1/competitions/invitations/accept'
    | '/api/v1/game-data/clubs/$externalClubId'
    | '/api/v1/game-data/clubs/search'
    | '/api/v1/identity/onboarding/invitation'
    | '/api/v1/identity/onboarding/organization'
    | '/api/v1/identity/onboarding/player'
    | '/api/v1/organizations/$organizationId/competitions'
    | '/api/v1/organizations/$organizationId/invitations'
    | '/api/v1/organizations/$organizationId/teams'
    | '/api/v1/organizations/invitations/accept'
    | '/api/v1/players/me/active-team'
    | '/api/v1/players/me/game-accounts'
    | '/api/v1/players/me/teams'
    | '/orgs/$orgId/competitions/'
    | '/orgs/$orgId/competitions/$competitionId/setup'
    | '/orgs/$orgId/competitions/$competitionId/teams'
    | '/api/v1/game-data/clubs/$externalClubId/matches'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId'
    | '/orgs/$orgId/competitions/$competitionId/'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/invitations'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/participants'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/publish'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/team-management'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/participants/$entryId'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/team-management/$teamId'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/entries/$entryId/$decision'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/external-club'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster-invitations'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster/$membershipId'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster/close'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster/open'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/player'
    | '/login'
    | '/signup'
    | '/onboarding/competition'
    | '/onboarding/game'
    | '/onboarding/game-account'
    | '/onboarding/intention'
    | '/onboarding/invitation'
    | '/onboarding/organization'
    | '/onboarding/review'
    | '/onboarding/team'
    | '/orgs/new'
    | '/player/competitions'
    | '/player/ea-clubs'
    | '/player/game-accounts'
    | '/roster-invitations/accept'
    | '/api/auth/$'
    | '/api/v1/openapi.json'
    | '/api/v1/openapi.yaml'
    | '/onboarding'
    | '/orgs'
    | '/invitations/accept/$plainToken'
    | '/roster-invitations/accept/$token'
    | '/api/v1/authorization/effective-access'
    | '/api/v1/competitions/mine'
    | '/api/v1/identity/onboarding'
    | '/api/v1/meta/ping'
    | '/api/v1/organizations/mine'
    | '/api/v1/organizations/name-availability'
    | '/api/v1/organizations/post-auth-destination'
    | '/api/v1/players/me'
    | '/api/v1/roster-invitations/accept'
    | '/invitations/accept'
    | '/orgs/$orgId'
    | '/api/v1/organizations'
    | '/orgs/$orgId/competitions/new'
    | '/api/v1/competitions/invitations/accept'
    | '/api/v1/game-data/clubs/$externalClubId'
    | '/api/v1/game-data/clubs/search'
    | '/api/v1/identity/onboarding/invitation'
    | '/api/v1/identity/onboarding/organization'
    | '/api/v1/identity/onboarding/player'
    | '/api/v1/organizations/$organizationId/competitions'
    | '/api/v1/organizations/$organizationId/invitations'
    | '/api/v1/organizations/$organizationId/teams'
    | '/api/v1/organizations/invitations/accept'
    | '/api/v1/players/me/active-team'
    | '/api/v1/players/me/game-accounts'
    | '/api/v1/players/me/teams'
    | '/orgs/$orgId/competitions'
    | '/orgs/$orgId/competitions/$competitionId/setup'
    | '/orgs/$orgId/competitions/$competitionId/teams'
    | '/api/v1/game-data/clubs/$externalClubId/matches'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId'
    | '/orgs/$orgId/competitions/$competitionId'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/invitations'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/participants'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/publish'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/team-management'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/participants/$entryId'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/team-management/$teamId'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/entries/$entryId/$decision'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/external-club'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster-invitations'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster/$membershipId'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster/close'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster/open'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/onboarding'
    | '/_app/player'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_app/onboarding/competition'
    | '/_app/onboarding/game'
    | '/_app/onboarding/game-account'
    | '/_app/onboarding/intention'
    | '/_app/onboarding/invitation'
    | '/_app/onboarding/organization'
    | '/_app/onboarding/review'
    | '/_app/onboarding/team'
    | '/_app/orgs/new'
    | '/_app/player_/competitions'
    | '/_app/player_/ea-clubs'
    | '/_app/player_/game-accounts'
    | '/_app/roster-invitations/accept'
    | '/api/auth/$'
    | '/api/v1/openapi.json'
    | '/api/v1/openapi.yaml'
    | '/_app/onboarding/'
    | '/_app/orgs/'
    | '/_app/invitations/accept/$plainToken'
    | '/_app/roster-invitations/accept/$token'
    | '/api/v1/authorization/effective-access'
    | '/api/v1/competitions/mine'
    | '/api/v1/identity/onboarding'
    | '/api/v1/meta/ping'
    | '/api/v1/organizations/mine'
    | '/api/v1/organizations/name-availability'
    | '/api/v1/organizations/post-auth-destination'
    | '/api/v1/players/me'
    | '/api/v1/roster-invitations/accept'
    | '/_app/invitations/accept/'
    | '/_app/orgs/$orgId/'
    | '/api/v1/organizations/'
    | '/_app/orgs/$orgId/competitions/new'
    | '/api/v1/competitions/invitations/accept'
    | '/api/v1/game-data/clubs/$externalClubId'
    | '/api/v1/game-data/clubs/search'
    | '/api/v1/identity/onboarding/invitation'
    | '/api/v1/identity/onboarding/organization'
    | '/api/v1/identity/onboarding/player'
    | '/api/v1/organizations/$organizationId/competitions'
    | '/api/v1/organizations/$organizationId/invitations'
    | '/api/v1/organizations/$organizationId/teams'
    | '/api/v1/organizations/invitations/accept'
    | '/api/v1/players/me/active-team'
    | '/api/v1/players/me/game-accounts'
    | '/api/v1/players/me/teams'
    | '/_app/orgs/$orgId/competitions/'
    | '/_app/orgs/$orgId/competitions/$competitionId/setup'
    | '/_app/orgs/$orgId/competitions/$competitionId/teams'
    | '/api/v1/game-data/clubs/$externalClubId/matches'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId'
    | '/_app/orgs/$orgId/competitions/$competitionId/'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/invitations'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/participants'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/publish'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/team-management'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/participants/$entryId'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/team-management/$teamId'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/entries/$entryId/$decision'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/external-club'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster-invitations'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster/$membershipId'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster/close'
    | '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster/open'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1OpenapiDotjsonRoute: typeof ApiV1OpenapiDotjsonRoute
  ApiV1OpenapiDotyamlRoute: typeof ApiV1OpenapiDotyamlRoute
  ApiV1AuthorizationEffectiveAccessRoute: typeof ApiV1AuthorizationEffectiveAccessRoute
  ApiV1CompetitionsMineRoute: typeof ApiV1CompetitionsMineRoute
  ApiV1IdentityOnboardingRoute: typeof ApiV1IdentityOnboardingRouteWithChildren
  ApiV1MetaPingRoute: typeof ApiV1MetaPingRoute
  ApiV1OrganizationsMineRoute: typeof ApiV1OrganizationsMineRoute
  ApiV1OrganizationsNameAvailabilityRoute: typeof ApiV1OrganizationsNameAvailabilityRoute
  ApiV1OrganizationsPostAuthDestinationRoute: typeof ApiV1OrganizationsPostAuthDestinationRoute
  ApiV1PlayersMeRoute: typeof ApiV1PlayersMeRouteWithChildren
  ApiV1RosterInvitationsAcceptRoute: typeof ApiV1RosterInvitationsAcceptRoute
  ApiV1OrganizationsIndexRoute: typeof ApiV1OrganizationsIndexRoute
  ApiV1CompetitionsInvitationsAcceptRoute: typeof ApiV1CompetitionsInvitationsAcceptRoute
  ApiV1GameDataClubsExternalClubIdRoute: typeof ApiV1GameDataClubsExternalClubIdRouteWithChildren
  ApiV1GameDataClubsSearchRoute: typeof ApiV1GameDataClubsSearchRoute
  ApiV1OrganizationsOrganizationIdCompetitionsRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsRouteWithChildren
  ApiV1OrganizationsOrganizationIdInvitationsRoute: typeof ApiV1OrganizationsOrganizationIdInvitationsRoute
  ApiV1OrganizationsOrganizationIdTeamsRoute: typeof ApiV1OrganizationsOrganizationIdTeamsRoute
  ApiV1OrganizationsInvitationsAcceptRoute: typeof ApiV1OrganizationsInvitationsAcceptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/player': {
      id: '/_app/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof AppPlayerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orgs/': {
      id: '/_app/orgs/'
      path: '/orgs'
      fullPath: '/orgs/'
      preLoaderRoute: typeof AppOrgsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding/': {
      id: '/_app/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AppOnboardingIndexRouteImport
      parentRoute: typeof AppOnboardingRoute
    }
    '/api/v1/openapi.yaml': {
      id: '/api/v1/openapi.yaml'
      path: '/api/v1/openapi.yaml'
      fullPath: '/api/v1/openapi.yaml'
      preLoaderRoute: typeof ApiV1OpenapiDotyamlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/openapi.json': {
      id: '/api/v1/openapi.json'
      path: '/api/v1/openapi.json'
      fullPath: '/api/v1/openapi.json'
      preLoaderRoute: typeof ApiV1OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/roster-invitations/accept': {
      id: '/_app/roster-invitations/accept'
      path: '/roster-invitations/accept'
      fullPath: '/roster-invitations/accept'
      preLoaderRoute: typeof AppRosterInvitationsAcceptRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/player_/game-accounts': {
      id: '/_app/player_/game-accounts'
      path: '/player/game-accounts'
      fullPath: '/player/game-accounts'
      preLoaderRoute: typeof AppPlayerGameAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/player_/ea-clubs': {
      id: '/_app/player_/ea-clubs'
      path: '/player/ea-clubs'
      fullPath: '/player/ea-clubs'
      preLoaderRoute: typeof AppPlayerEaClubsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/player_/competitions': {
      id: '/_app/player_/competitions'
      path: '/player/competitions'
      fullPath: '/player/competitions'
      preLoaderRoute: typeof AppPlayerCompetitionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orgs/new': {
      id: '/_app/orgs/new'
      path: '/orgs/new'
      fullPath: '/orgs/new'
      preLoaderRoute: typeof AppOrgsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding/team': {
      id: '/_app/onboarding/team'
      path: '/team'
      fullPath: '/onboarding/team'
      preLoaderRoute: typeof AppOnboardingTeamRouteImport
      parentRoute: typeof AppOnboardingRoute
    }
    '/_app/onboarding/review': {
      id: '/_app/onboarding/review'
      path: '/review'
      fullPath: '/onboarding/review'
      preLoaderRoute: typeof AppOnboardingReviewRouteImport
      parentRoute: typeof AppOnboardingRoute
    }
    '/_app/onboarding/organization': {
      id: '/_app/onboarding/organization'
      path: '/organization'
      fullPath: '/onboarding/organization'
      preLoaderRoute: typeof AppOnboardingOrganizationRouteImport
      parentRoute: typeof AppOnboardingRoute
    }
    '/_app/onboarding/invitation': {
      id: '/_app/onboarding/invitation'
      path: '/invitation'
      fullPath: '/onboarding/invitation'
      preLoaderRoute: typeof AppOnboardingInvitationRouteImport
      parentRoute: typeof AppOnboardingRoute
    }
    '/_app/onboarding/intention': {
      id: '/_app/onboarding/intention'
      path: '/intention'
      fullPath: '/onboarding/intention'
      preLoaderRoute: typeof AppOnboardingIntentionRouteImport
      parentRoute: typeof AppOnboardingRoute
    }
    '/_app/onboarding/game-account': {
      id: '/_app/onboarding/game-account'
      path: '/game-account'
      fullPath: '/onboarding/game-account'
      preLoaderRoute: typeof AppOnboardingGameAccountRouteImport
      parentRoute: typeof AppOnboardingRoute
    }
    '/_app/onboarding/game': {
      id: '/_app/onboarding/game'
      path: '/game'
      fullPath: '/onboarding/game'
      preLoaderRoute: typeof AppOnboardingGameRouteImport
      parentRoute: typeof AppOnboardingRoute
    }
    '/_app/onboarding/competition': {
      id: '/_app/onboarding/competition'
      path: '/competition'
      fullPath: '/onboarding/competition'
      preLoaderRoute: typeof AppOnboardingCompetitionRouteImport
      parentRoute: typeof AppOnboardingRoute
    }
    '/api/v1/organizations/': {
      id: '/api/v1/organizations/'
      path: '/api/v1/organizations'
      fullPath: '/api/v1/organizations/'
      preLoaderRoute: typeof ApiV1OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/orgs/$orgId/': {
      id: '/_app/orgs/$orgId/'
      path: '/orgs/$orgId'
      fullPath: '/orgs/$orgId/'
      preLoaderRoute: typeof AppOrgsOrgIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invitations/accept/': {
      id: '/_app/invitations/accept/'
      path: '/invitations/accept'
      fullPath: '/invitations/accept/'
      preLoaderRoute: typeof AppInvitationsAcceptIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/v1/roster-invitations/accept': {
      id: '/api/v1/roster-invitations/accept'
      path: '/api/v1/roster-invitations/accept'
      fullPath: '/api/v1/roster-invitations/accept'
      preLoaderRoute: typeof ApiV1RosterInvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/players/me': {
      id: '/api/v1/players/me'
      path: '/api/v1/players/me'
      fullPath: '/api/v1/players/me'
      preLoaderRoute: typeof ApiV1PlayersMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/organizations/post-auth-destination': {
      id: '/api/v1/organizations/post-auth-destination'
      path: '/api/v1/organizations/post-auth-destination'
      fullPath: '/api/v1/organizations/post-auth-destination'
      preLoaderRoute: typeof ApiV1OrganizationsPostAuthDestinationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/organizations/name-availability': {
      id: '/api/v1/organizations/name-availability'
      path: '/api/v1/organizations/name-availability'
      fullPath: '/api/v1/organizations/name-availability'
      preLoaderRoute: typeof ApiV1OrganizationsNameAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/organizations/mine': {
      id: '/api/v1/organizations/mine'
      path: '/api/v1/organizations/mine'
      fullPath: '/api/v1/organizations/mine'
      preLoaderRoute: typeof ApiV1OrganizationsMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/meta/ping': {
      id: '/api/v1/meta/ping'
      path: '/api/v1/meta/ping'
      fullPath: '/api/v1/meta/ping'
      preLoaderRoute: typeof ApiV1MetaPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/identity/onboarding': {
      id: '/api/v1/identity/onboarding'
      path: '/api/v1/identity/onboarding'
      fullPath: '/api/v1/identity/onboarding'
      preLoaderRoute: typeof ApiV1IdentityOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/competitions/mine': {
      id: '/api/v1/competitions/mine'
      path: '/api/v1/competitions/mine'
      fullPath: '/api/v1/competitions/mine'
      preLoaderRoute: typeof ApiV1CompetitionsMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/authorization/effective-access': {
      id: '/api/v1/authorization/effective-access'
      path: '/api/v1/authorization/effective-access'
      fullPath: '/api/v1/authorization/effective-access'
      preLoaderRoute: typeof ApiV1AuthorizationEffectiveAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/roster-invitations/accept/$token': {
      id: '/_app/roster-invitations/accept/$token'
      path: '/$token'
      fullPath: '/roster-invitations/accept/$token'
      preLoaderRoute: typeof AppRosterInvitationsAcceptTokenRouteImport
      parentRoute: typeof AppRosterInvitationsAcceptRoute
    }
    '/_app/invitations/accept/$plainToken': {
      id: '/_app/invitations/accept/$plainToken'
      path: '/invitations/accept/$plainToken'
      fullPath: '/invitations/accept/$plainToken'
      preLoaderRoute: typeof AppInvitationsAcceptPlainTokenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orgs/$orgId/competitions/': {
      id: '/_app/orgs/$orgId/competitions/'
      path: '/orgs/$orgId/competitions'
      fullPath: '/orgs/$orgId/competitions/'
      preLoaderRoute: typeof AppOrgsOrgIdCompetitionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/v1/players/me/teams': {
      id: '/api/v1/players/me/teams'
      path: '/teams'
      fullPath: '/api/v1/players/me/teams'
      preLoaderRoute: typeof ApiV1PlayersMeTeamsRouteImport
      parentRoute: typeof ApiV1PlayersMeRoute
    }
    '/api/v1/players/me/game-accounts': {
      id: '/api/v1/players/me/game-accounts'
      path: '/game-accounts'
      fullPath: '/api/v1/players/me/game-accounts'
      preLoaderRoute: typeof ApiV1PlayersMeGameAccountsRouteImport
      parentRoute: typeof ApiV1PlayersMeRoute
    }
    '/api/v1/players/me/active-team': {
      id: '/api/v1/players/me/active-team'
      path: '/active-team'
      fullPath: '/api/v1/players/me/active-team'
      preLoaderRoute: typeof ApiV1PlayersMeActiveTeamRouteImport
      parentRoute: typeof ApiV1PlayersMeRoute
    }
    '/api/v1/organizations/invitations/accept': {
      id: '/api/v1/organizations/invitations/accept'
      path: '/api/v1/organizations/invitations/accept'
      fullPath: '/api/v1/organizations/invitations/accept'
      preLoaderRoute: typeof ApiV1OrganizationsInvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/organizations/$organizationId/teams': {
      id: '/api/v1/organizations/$organizationId/teams'
      path: '/api/v1/organizations/$organizationId/teams'
      fullPath: '/api/v1/organizations/$organizationId/teams'
      preLoaderRoute: typeof ApiV1OrganizationsOrganizationIdTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/organizations/$organizationId/invitations': {
      id: '/api/v1/organizations/$organizationId/invitations'
      path: '/api/v1/organizations/$organizationId/invitations'
      fullPath: '/api/v1/organizations/$organizationId/invitations'
      preLoaderRoute: typeof ApiV1OrganizationsOrganizationIdInvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/organizations/$organizationId/competitions': {
      id: '/api/v1/organizations/$organizationId/competitions'
      path: '/api/v1/organizations/$organizationId/competitions'
      fullPath: '/api/v1/organizations/$organizationId/competitions'
      preLoaderRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/identity/onboarding/player': {
      id: '/api/v1/identity/onboarding/player'
      path: '/player'
      fullPath: '/api/v1/identity/onboarding/player'
      preLoaderRoute: typeof ApiV1IdentityOnboardingPlayerRouteImport
      parentRoute: typeof ApiV1IdentityOnboardingRoute
    }
    '/api/v1/identity/onboarding/organization': {
      id: '/api/v1/identity/onboarding/organization'
      path: '/organization'
      fullPath: '/api/v1/identity/onboarding/organization'
      preLoaderRoute: typeof ApiV1IdentityOnboardingOrganizationRouteImport
      parentRoute: typeof ApiV1IdentityOnboardingRoute
    }
    '/api/v1/identity/onboarding/invitation': {
      id: '/api/v1/identity/onboarding/invitation'
      path: '/invitation'
      fullPath: '/api/v1/identity/onboarding/invitation'
      preLoaderRoute: typeof ApiV1IdentityOnboardingInvitationRouteImport
      parentRoute: typeof ApiV1IdentityOnboardingRoute
    }
    '/api/v1/game-data/clubs/search': {
      id: '/api/v1/game-data/clubs/search'
      path: '/api/v1/game-data/clubs/search'
      fullPath: '/api/v1/game-data/clubs/search'
      preLoaderRoute: typeof ApiV1GameDataClubsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/game-data/clubs/$externalClubId': {
      id: '/api/v1/game-data/clubs/$externalClubId'
      path: '/api/v1/game-data/clubs/$externalClubId'
      fullPath: '/api/v1/game-data/clubs/$externalClubId'
      preLoaderRoute: typeof ApiV1GameDataClubsExternalClubIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/competitions/invitations/accept': {
      id: '/api/v1/competitions/invitations/accept'
      path: '/api/v1/competitions/invitations/accept'
      fullPath: '/api/v1/competitions/invitations/accept'
      preLoaderRoute: typeof ApiV1CompetitionsInvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/orgs/$orgId/competitions/new': {
      id: '/_app/orgs/$orgId/competitions/new'
      path: '/orgs/$orgId/competitions/new'
      fullPath: '/orgs/$orgId/competitions/new'
      preLoaderRoute: typeof AppOrgsOrgIdCompetitionsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orgs/$orgId/competitions/$competitionId/': {
      id: '/_app/orgs/$orgId/competitions/$competitionId/'
      path: '/orgs/$orgId/competitions/$competitionId'
      fullPath: '/orgs/$orgId/competitions/$competitionId/'
      preLoaderRoute: typeof AppOrgsOrgIdCompetitionsCompetitionIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/v1/organizations/$organizationId/competitions/$competitionId': {
      id: '/api/v1/organizations/$organizationId/competitions/$competitionId'
      path: '/$competitionId'
      fullPath: '/api/v1/organizations/$organizationId/competitions/$competitionId'
      preLoaderRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRouteImport
      parentRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsRoute
    }
    '/api/v1/game-data/clubs/$externalClubId/matches': {
      id: '/api/v1/game-data/clubs/$externalClubId/matches'
      path: '/matches'
      fullPath: '/api/v1/game-data/clubs/$externalClubId/matches'
      preLoaderRoute: typeof ApiV1GameDataClubsExternalClubIdMatchesRouteImport
      parentRoute: typeof ApiV1GameDataClubsExternalClubIdRoute
    }
    '/_app/orgs/$orgId/competitions/$competitionId/teams': {
      id: '/_app/orgs/$orgId/competitions/$competitionId/teams'
      path: '/orgs/$orgId/competitions/$competitionId/teams'
      fullPath: '/orgs/$orgId/competitions/$competitionId/teams'
      preLoaderRoute: typeof AppOrgsOrgIdCompetitionsCompetitionIdTeamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orgs/$orgId/competitions/$competitionId/setup': {
      id: '/_app/orgs/$orgId/competitions/$competitionId/setup'
      path: '/orgs/$orgId/competitions/$competitionId/setup'
      fullPath: '/orgs/$orgId/competitions/$competitionId/setup'
      preLoaderRoute: typeof AppOrgsOrgIdCompetitionsCompetitionIdSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/v1/organizations/$organizationId/competitions/$competitionId/team-management': {
      id: '/api/v1/organizations/$organizationId/competitions/$competitionId/team-management'
      path: '/team-management'
      fullPath: '/api/v1/organizations/$organizationId/competitions/$competitionId/team-management'
      preLoaderRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamManagementRouteImport
      parentRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRoute
    }
    '/api/v1/organizations/$organizationId/competitions/$competitionId/publish': {
      id: '/api/v1/organizations/$organizationId/competitions/$competitionId/publish'
      path: '/publish'
      fullPath: '/api/v1/organizations/$organizationId/competitions/$competitionId/publish'
      preLoaderRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdPublishRouteImport
      parentRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRoute
    }
    '/api/v1/organizations/$organizationId/competitions/$competitionId/participants': {
      id: '/api/v1/organizations/$organizationId/competitions/$competitionId/participants'
      path: '/participants'
      fullPath: '/api/v1/organizations/$organizationId/competitions/$competitionId/participants'
      preLoaderRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdParticipantsRouteImport
      parentRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRoute
    }
    '/api/v1/organizations/$organizationId/competitions/$competitionId/invitations': {
      id: '/api/v1/organizations/$organizationId/competitions/$competitionId/invitations'
      path: '/invitations'
      fullPath: '/api/v1/organizations/$organizationId/competitions/$competitionId/invitations'
      preLoaderRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdInvitationsRouteImport
      parentRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRoute
    }
    '/api/v1/organizations/$organizationId/competitions/$competitionId/team-management/$teamId': {
      id: '/api/v1/organizations/$organizationId/competitions/$competitionId/team-management/$teamId'
      path: '/$teamId'
      fullPath: '/api/v1/organizations/$organizationId/competitions/$competitionId/team-management/$teamId'
      preLoaderRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamManagementTeamIdRouteImport
      parentRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamManagementRoute
    }
    '/api/v1/organizations/$organizationId/competitions/$competitionId/participants/$entryId': {
      id: '/api/v1/organizations/$organizationId/competitions/$competitionId/participants/$entryId'
      path: '/$entryId'
      fullPath: '/api/v1/organizations/$organizationId/competitions/$competitionId/participants/$entryId'
      preLoaderRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdParticipantsEntryIdRouteImport
      parentRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdParticipantsRoute
    }
    '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster-invitations': {
      id: '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster-invitations'
      path: '/teams/$teamId/roster-invitations'
      fullPath: '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster-invitations'
      preLoaderRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterInvitationsRouteImport
      parentRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRoute
    }
    '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/external-club': {
      id: '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/external-club'
      path: '/teams/$teamId/external-club'
      fullPath: '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/external-club'
      preLoaderRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdExternalClubRouteImport
      parentRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRoute
    }
    '/api/v1/organizations/$organizationId/competitions/$competitionId/entries/$entryId/$decision': {
      id: '/api/v1/organizations/$organizationId/competitions/$competitionId/entries/$entryId/$decision'
      path: '/entries/$entryId/$decision'
      fullPath: '/api/v1/organizations/$organizationId/competitions/$competitionId/entries/$entryId/$decision'
      preLoaderRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdEntriesEntryIdDecisionRouteImport
      parentRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRoute
    }
    '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster/open': {
      id: '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster/open'
      path: '/teams/$teamId/roster/open'
      fullPath: '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster/open'
      preLoaderRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterOpenRouteImport
      parentRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRoute
    }
    '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster/close': {
      id: '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster/close'
      path: '/teams/$teamId/roster/close'
      fullPath: '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster/close'
      preLoaderRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterCloseRouteImport
      parentRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRoute
    }
    '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster/$membershipId': {
      id: '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster/$membershipId'
      path: '/teams/$teamId/roster/$membershipId'
      fullPath: '/api/v1/organizations/$organizationId/competitions/$competitionId/teams/$teamId/roster/$membershipId'
      preLoaderRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterMembershipIdRouteImport
      parentRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRoute
    }
  }
}

interface AppOnboardingRouteChildren {
  AppOnboardingCompetitionRoute: typeof AppOnboardingCompetitionRoute
  AppOnboardingGameRoute: typeof AppOnboardingGameRoute
  AppOnboardingGameAccountRoute: typeof AppOnboardingGameAccountRoute
  AppOnboardingIntentionRoute: typeof AppOnboardingIntentionRoute
  AppOnboardingInvitationRoute: typeof AppOnboardingInvitationRoute
  AppOnboardingOrganizationRoute: typeof AppOnboardingOrganizationRoute
  AppOnboardingReviewRoute: typeof AppOnboardingReviewRoute
  AppOnboardingTeamRoute: typeof AppOnboardingTeamRoute
  AppOnboardingIndexRoute: typeof AppOnboardingIndexRoute
}

const AppOnboardingRouteChildren: AppOnboardingRouteChildren = {
  AppOnboardingCompetitionRoute: AppOnboardingCompetitionRoute,
  AppOnboardingGameRoute: AppOnboardingGameRoute,
  AppOnboardingGameAccountRoute: AppOnboardingGameAccountRoute,
  AppOnboardingIntentionRoute: AppOnboardingIntentionRoute,
  AppOnboardingInvitationRoute: AppOnboardingInvitationRoute,
  AppOnboardingOrganizationRoute: AppOnboardingOrganizationRoute,
  AppOnboardingReviewRoute: AppOnboardingReviewRoute,
  AppOnboardingTeamRoute: AppOnboardingTeamRoute,
  AppOnboardingIndexRoute: AppOnboardingIndexRoute,
}

const AppOnboardingRouteWithChildren = AppOnboardingRoute._addFileChildren(
  AppOnboardingRouteChildren,
)

interface AppRosterInvitationsAcceptRouteChildren {
  AppRosterInvitationsAcceptTokenRoute: typeof AppRosterInvitationsAcceptTokenRoute
}

const AppRosterInvitationsAcceptRouteChildren: AppRosterInvitationsAcceptRouteChildren =
  {
    AppRosterInvitationsAcceptTokenRoute: AppRosterInvitationsAcceptTokenRoute,
  }

const AppRosterInvitationsAcceptRouteWithChildren =
  AppRosterInvitationsAcceptRoute._addFileChildren(
    AppRosterInvitationsAcceptRouteChildren,
  )

interface AppRouteChildren {
  AppOnboardingRoute: typeof AppOnboardingRouteWithChildren
  AppPlayerRoute: typeof AppPlayerRoute
  AppOrgsNewRoute: typeof AppOrgsNewRoute
  AppPlayerCompetitionsRoute: typeof AppPlayerCompetitionsRoute
  AppPlayerEaClubsRoute: typeof AppPlayerEaClubsRoute
  AppPlayerGameAccountsRoute: typeof AppPlayerGameAccountsRoute
  AppRosterInvitationsAcceptRoute: typeof AppRosterInvitationsAcceptRouteWithChildren
  AppOrgsIndexRoute: typeof AppOrgsIndexRoute
  AppInvitationsAcceptPlainTokenRoute: typeof AppInvitationsAcceptPlainTokenRoute
  AppInvitationsAcceptIndexRoute: typeof AppInvitationsAcceptIndexRoute
  AppOrgsOrgIdIndexRoute: typeof AppOrgsOrgIdIndexRoute
  AppOrgsOrgIdCompetitionsNewRoute: typeof AppOrgsOrgIdCompetitionsNewRoute
  AppOrgsOrgIdCompetitionsIndexRoute: typeof AppOrgsOrgIdCompetitionsIndexRoute
  AppOrgsOrgIdCompetitionsCompetitionIdSetupRoute: typeof AppOrgsOrgIdCompetitionsCompetitionIdSetupRoute
  AppOrgsOrgIdCompetitionsCompetitionIdTeamsRoute: typeof AppOrgsOrgIdCompetitionsCompetitionIdTeamsRoute
  AppOrgsOrgIdCompetitionsCompetitionIdIndexRoute: typeof AppOrgsOrgIdCompetitionsCompetitionIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppOnboardingRoute: AppOnboardingRouteWithChildren,
  AppPlayerRoute: AppPlayerRoute,
  AppOrgsNewRoute: AppOrgsNewRoute,
  AppPlayerCompetitionsRoute: AppPlayerCompetitionsRoute,
  AppPlayerEaClubsRoute: AppPlayerEaClubsRoute,
  AppPlayerGameAccountsRoute: AppPlayerGameAccountsRoute,
  AppRosterInvitationsAcceptRoute: AppRosterInvitationsAcceptRouteWithChildren,
  AppOrgsIndexRoute: AppOrgsIndexRoute,
  AppInvitationsAcceptPlainTokenRoute: AppInvitationsAcceptPlainTokenRoute,
  AppInvitationsAcceptIndexRoute: AppInvitationsAcceptIndexRoute,
  AppOrgsOrgIdIndexRoute: AppOrgsOrgIdIndexRoute,
  AppOrgsOrgIdCompetitionsNewRoute: AppOrgsOrgIdCompetitionsNewRoute,
  AppOrgsOrgIdCompetitionsIndexRoute: AppOrgsOrgIdCompetitionsIndexRoute,
  AppOrgsOrgIdCompetitionsCompetitionIdSetupRoute:
    AppOrgsOrgIdCompetitionsCompetitionIdSetupRoute,
  AppOrgsOrgIdCompetitionsCompetitionIdTeamsRoute:
    AppOrgsOrgIdCompetitionsCompetitionIdTeamsRoute,
  AppOrgsOrgIdCompetitionsCompetitionIdIndexRoute:
    AppOrgsOrgIdCompetitionsCompetitionIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ApiV1IdentityOnboardingRouteChildren {
  ApiV1IdentityOnboardingInvitationRoute: typeof ApiV1IdentityOnboardingInvitationRoute
  ApiV1IdentityOnboardingOrganizationRoute: typeof ApiV1IdentityOnboardingOrganizationRoute
  ApiV1IdentityOnboardingPlayerRoute: typeof ApiV1IdentityOnboardingPlayerRoute
}

const ApiV1IdentityOnboardingRouteChildren: ApiV1IdentityOnboardingRouteChildren =
  {
    ApiV1IdentityOnboardingInvitationRoute:
      ApiV1IdentityOnboardingInvitationRoute,
    ApiV1IdentityOnboardingOrganizationRoute:
      ApiV1IdentityOnboardingOrganizationRoute,
    ApiV1IdentityOnboardingPlayerRoute: ApiV1IdentityOnboardingPlayerRoute,
  }

const ApiV1IdentityOnboardingRouteWithChildren =
  ApiV1IdentityOnboardingRoute._addFileChildren(
    ApiV1IdentityOnboardingRouteChildren,
  )

interface ApiV1PlayersMeRouteChildren {
  ApiV1PlayersMeActiveTeamRoute: typeof ApiV1PlayersMeActiveTeamRoute
  ApiV1PlayersMeGameAccountsRoute: typeof ApiV1PlayersMeGameAccountsRoute
  ApiV1PlayersMeTeamsRoute: typeof ApiV1PlayersMeTeamsRoute
}

const ApiV1PlayersMeRouteChildren: ApiV1PlayersMeRouteChildren = {
  ApiV1PlayersMeActiveTeamRoute: ApiV1PlayersMeActiveTeamRoute,
  ApiV1PlayersMeGameAccountsRoute: ApiV1PlayersMeGameAccountsRoute,
  ApiV1PlayersMeTeamsRoute: ApiV1PlayersMeTeamsRoute,
}

const ApiV1PlayersMeRouteWithChildren = ApiV1PlayersMeRoute._addFileChildren(
  ApiV1PlayersMeRouteChildren,
)

interface ApiV1GameDataClubsExternalClubIdRouteChildren {
  ApiV1GameDataClubsExternalClubIdMatchesRoute: typeof ApiV1GameDataClubsExternalClubIdMatchesRoute
}

const ApiV1GameDataClubsExternalClubIdRouteChildren: ApiV1GameDataClubsExternalClubIdRouteChildren =
  {
    ApiV1GameDataClubsExternalClubIdMatchesRoute:
      ApiV1GameDataClubsExternalClubIdMatchesRoute,
  }

const ApiV1GameDataClubsExternalClubIdRouteWithChildren =
  ApiV1GameDataClubsExternalClubIdRoute._addFileChildren(
    ApiV1GameDataClubsExternalClubIdRouteChildren,
  )

interface ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdParticipantsRouteChildren {
  ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdParticipantsEntryIdRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdParticipantsEntryIdRoute
}

const ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdParticipantsRouteChildren: ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdParticipantsRouteChildren =
  {
    ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdParticipantsEntryIdRoute:
      ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdParticipantsEntryIdRoute,
  }

const ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdParticipantsRouteWithChildren =
  ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdParticipantsRoute._addFileChildren(
    ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdParticipantsRouteChildren,
  )

interface ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamManagementRouteChildren {
  ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamManagementTeamIdRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamManagementTeamIdRoute
}

const ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamManagementRouteChildren: ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamManagementRouteChildren =
  {
    ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamManagementTeamIdRoute:
      ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamManagementTeamIdRoute,
  }

const ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamManagementRouteWithChildren =
  ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamManagementRoute._addFileChildren(
    ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamManagementRouteChildren,
  )

interface ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRouteChildren {
  ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdInvitationsRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdInvitationsRoute
  ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdParticipantsRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdParticipantsRouteWithChildren
  ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdPublishRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdPublishRoute
  ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamManagementRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamManagementRouteWithChildren
  ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdEntriesEntryIdDecisionRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdEntriesEntryIdDecisionRoute
  ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdExternalClubRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdExternalClubRoute
  ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterInvitationsRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterInvitationsRoute
  ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterMembershipIdRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterMembershipIdRoute
  ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterCloseRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterCloseRoute
  ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterOpenRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterOpenRoute
}

const ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRouteChildren: ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRouteChildren =
  {
    ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdInvitationsRoute:
      ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdInvitationsRoute,
    ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdParticipantsRoute:
      ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdParticipantsRouteWithChildren,
    ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdPublishRoute:
      ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdPublishRoute,
    ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamManagementRoute:
      ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamManagementRouteWithChildren,
    ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdEntriesEntryIdDecisionRoute:
      ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdEntriesEntryIdDecisionRoute,
    ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdExternalClubRoute:
      ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdExternalClubRoute,
    ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterInvitationsRoute:
      ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterInvitationsRoute,
    ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterMembershipIdRoute:
      ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterMembershipIdRoute,
    ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterCloseRoute:
      ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterCloseRoute,
    ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterOpenRoute:
      ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdTeamsTeamIdRosterOpenRoute,
  }

const ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRouteWithChildren =
  ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRoute._addFileChildren(
    ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRouteChildren,
  )

interface ApiV1OrganizationsOrganizationIdCompetitionsRouteChildren {
  ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRoute: typeof ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRouteWithChildren
}

const ApiV1OrganizationsOrganizationIdCompetitionsRouteChildren: ApiV1OrganizationsOrganizationIdCompetitionsRouteChildren =
  {
    ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRoute:
      ApiV1OrganizationsOrganizationIdCompetitionsCompetitionIdRouteWithChildren,
  }

const ApiV1OrganizationsOrganizationIdCompetitionsRouteWithChildren =
  ApiV1OrganizationsOrganizationIdCompetitionsRoute._addFileChildren(
    ApiV1OrganizationsOrganizationIdCompetitionsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1OpenapiDotjsonRoute: ApiV1OpenapiDotjsonRoute,
  ApiV1OpenapiDotyamlRoute: ApiV1OpenapiDotyamlRoute,
  ApiV1AuthorizationEffectiveAccessRoute:
    ApiV1AuthorizationEffectiveAccessRoute,
  ApiV1CompetitionsMineRoute: ApiV1CompetitionsMineRoute,
  ApiV1IdentityOnboardingRoute: ApiV1IdentityOnboardingRouteWithChildren,
  ApiV1MetaPingRoute: ApiV1MetaPingRoute,
  ApiV1OrganizationsMineRoute: ApiV1OrganizationsMineRoute,
  ApiV1OrganizationsNameAvailabilityRoute:
    ApiV1OrganizationsNameAvailabilityRoute,
  ApiV1OrganizationsPostAuthDestinationRoute:
    ApiV1OrganizationsPostAuthDestinationRoute,
  ApiV1PlayersMeRoute: ApiV1PlayersMeRouteWithChildren,
  ApiV1RosterInvitationsAcceptRoute: ApiV1RosterInvitationsAcceptRoute,
  ApiV1OrganizationsIndexRoute: ApiV1OrganizationsIndexRoute,
  ApiV1CompetitionsInvitationsAcceptRoute:
    ApiV1CompetitionsInvitationsAcceptRoute,
  ApiV1GameDataClubsExternalClubIdRoute:
    ApiV1GameDataClubsExternalClubIdRouteWithChildren,
  ApiV1GameDataClubsSearchRoute: ApiV1GameDataClubsSearchRoute,
  ApiV1OrganizationsOrganizationIdCompetitionsRoute:
    ApiV1OrganizationsOrganizationIdCompetitionsRouteWithChildren,
  ApiV1OrganizationsOrganizationIdInvitationsRoute:
    ApiV1OrganizationsOrganizationIdInvitationsRoute,
  ApiV1OrganizationsOrganizationIdTeamsRoute:
    ApiV1OrganizationsOrganizationIdTeamsRoute,
  ApiV1OrganizationsInvitationsAcceptRoute:
    ApiV1OrganizationsInvitationsAcceptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
