import {
  LightningIcon,
  LinkSimpleIcon,
  ListIcon,
  ListChecksIcon,
  LockIcon,
  MagnifyingGlassIcon,
  MinusIcon,
  MonitorIcon,
  PersonSimpleThrowIcon,
  PlusIcon,
  PlugsIcon,
  RectangleIcon,
  ScalesIcon,
  ShieldIcon,
  SidebarIcon,
  SidebarSimpleIcon,
  SignpostIcon,
  SoccerBallIcon,
  StarIcon,
  SwordIcon,
  TicketIcon,
  TrayIcon,
  TrendDownIcon,
  TrendUpIcon,
  TrophyIcon,
  UserIcon,
  UsersIcon,
  UsersThreeIcon,
  WarningIcon,
  WarningCircleIcon,
  XIcon,
} from "@phosphor-icons/react";
import type { FutrobIconEntry } from "./catalog.ts";

/** Second half of the Phosphor inventory used by `@futrob/ui` and `apps/web`. */
export const FUTROB_ICON_CATALOG_B = [
  {
    name: "LightningIcon",
    label: "Rayo",
    usage: "Acción rápida y highlights",
    Icon: LightningIcon,
  },
  {
    name: "LinkSimpleIcon",
    label: "Enlace",
    usage: "URLs e invitaciones compartibles",
    Icon: LinkSimpleIcon,
  },
  {
    name: "ListIcon",
    label: "Menú",
    usage: "Abrir navegación móvil (sheet)",
    Icon: ListIcon,
  },
  {
    name: "ListChecksIcon",
    label: "Lista de tareas",
    usage: "Checklist de setup de competición",
    Icon: ListChecksIcon,
  },
  {
    name: "LockIcon",
    label: "Candado",
    usage: "Campos de contraseña",
    Icon: LockIcon,
  },
  {
    name: "MagnifyingGlassIcon",
    label: "Buscar",
    usage: "Inputs de búsqueda",
    Icon: MagnifyingGlassIcon,
  },
  {
    name: "MinusIcon",
    label: "Menos",
    usage: "Checkbox indeterminado",
    Icon: MinusIcon,
  },
  {
    name: "MonitorIcon",
    label: "Monitor",
    usage: "Plataforma genérica / fallback",
    Icon: MonitorIcon,
  },
  {
    name: "PersonSimpleThrowIcon",
    label: "Pase",
    usage: "Pase en el perfil de atributos del jugador",
    Icon: PersonSimpleThrowIcon,
  },
  {
    name: "PlusIcon",
    label: "Añadir",
    usage: "Crear / acciones primarias",
    Icon: PlusIcon,
  },
  {
    name: "PlugsIcon",
    label: "Desconexión",
    usage: "Partido ganado por DNF",
    Icon: PlugsIcon,
  },
  {
    name: "RectangleIcon",
    label: "Tarjeta",
    usage: "Tarjetas amarillas y rojas en Mis partidos",
    Icon: RectangleIcon,
  },
  {
    name: "ScalesIcon",
    label: "Balanza",
    usage: "Disciplina en el perfil de atributos del jugador",
    Icon: ScalesIcon,
  },
  {
    name: "ShieldIcon",
    label: "Escudo",
    usage: "Roles / revisión de onboarding",
    Icon: ShieldIcon,
  },
  {
    name: "SidebarIcon",
    label: "Expandir sidebar",
    usage: "Abrir barra lateral colapsada (alias SidebarExpandIcon si choca con el componente)",
    Icon: SidebarIcon,
  },
  {
    name: "SidebarSimpleIcon",
    label: "Colapsar sidebar",
    usage: "Cerrar barra lateral a icon rail",
    Icon: SidebarSimpleIcon,
  },
  {
    name: "SignpostIcon",
    label: "Señal",
    usage: "Camino / intención en onboarding",
    Icon: SignpostIcon,
  },
  {
    name: "SoccerBallIcon",
    label: "Balón",
    usage: "Goles y hat-trick en Mis partidos",
    Icon: SoccerBallIcon,
  },
  {
    name: "StarIcon",
    label: "Estrella",
    usage: "MVP en Mis partidos",
    Icon: StarIcon,
  },
  {
    name: "SwordIcon",
    label: "Espada",
    usage: "Ataque en el perfil de atributos del jugador",
    Icon: SwordIcon,
  },
  {
    name: "TicketIcon",
    label: "Invitación",
    usage: "Invitaciones a competición",
    Icon: TicketIcon,
  },
  {
    name: "TrayIcon",
    label: "Bandeja vacía",
    usage: "Empty states",
    Icon: TrayIcon,
  },
  {
    name: "TrendDownIcon",
    label: "Tendencia a la baja",
    usage: "Derrotas y rating a la baja en Mis partidos",
    Icon: TrendDownIcon,
  },
  {
    name: "TrendUpIcon",
    label: "Tendencia al alza",
    usage: "Rating al alza en Mis partidos",
    Icon: TrendUpIcon,
  },
  {
    name: "TrophyIcon",
    label: "Trofeo",
    usage: "Competiciones, rankings, victorias y tipo liga en Mis partidos",
    Icon: TrophyIcon,
  },
  {
    name: "UserIcon",
    label: "Usuario",
    usage: "Perfil / jugador individual",
    Icon: UserIcon,
  },
  {
    name: "UsersIcon",
    label: "Usuarios",
    usage: "Equipos",
    Icon: UsersIcon,
  },
  {
    name: "UsersThreeIcon",
    label: "Grupo",
    usage: "Jugadores / plantilla",
    Icon: UsersThreeIcon,
  },
  {
    name: "WarningIcon",
    label: "Advertencia",
    usage: "Alertas de tipo warning",
    Icon: WarningIcon,
  },
  {
    name: "WarningCircleIcon",
    label: "Error / alerta",
    usage: "Field errors y alertas destructivas",
    Icon: WarningCircleIcon,
  },
  {
    name: "XIcon",
    label: "Cerrar",
    usage: "Cerrar dialog / sheet",
    Icon: XIcon,
  },
] as const satisfies readonly FutrobIconEntry[];
