import type { Icon } from "@phosphor-icons/react";
import {
  ArrowCounterClockwiseIcon,
  ArrowDownRightIcon,
  ArrowUpRightIcon,
  BroadcastIcon,
  BuildingsIcon,
  CalendarDotsIcon,
  CaretDownIcon,
  CaretRightIcon,
  CheckIcon,
  CheckCircleIcon,
  CheckSquareOffsetIcon,
  CircleNotchIcon,
  CopyIcon,
  DotsThreeIcon,
  EnvelopeSimpleIcon,
  EyeIcon,
  EyeSlashIcon,
  GameControllerIcon,
  GearIcon,
  HouseIcon,
  InfoIcon,
  LinkSimpleIcon,
  ListIcon,
  ListChecksIcon,
  LockIcon,
  MagnifyingGlassIcon,
  MinusIcon,
  MonitorIcon,
  PlusIcon,
  ShieldIcon,
  SidebarIcon,
  SidebarSimpleIcon,
  SignpostIcon,
  TicketIcon,
  TrayIcon,
  TrophyIcon,
  UserIcon,
  UsersIcon,
  UsersThreeIcon,
  WarningIcon,
  WarningCircleIcon,
  XIcon,
} from "@phosphor-icons/react";

export type FutrobIconEntry = {
  readonly name: string;
  readonly label: string;
  readonly usage: string;
  readonly Icon: Icon;
};

/**
 * Every Phosphor icon referenced by `@futrob/ui` or `apps/web` presentation.
 * Keep this list in sync when adding or renaming product icons.
 * Prefer Phosphor `*Icon` exports (bare names are deprecated since 2.1.8).
 */
export const FUTROB_ICON_CATALOG = [
  {
    name: "ArrowCounterClockwiseIcon",
    label: "Reintentar",
    usage: "Acciones de refresh / reintentar",
    Icon: ArrowCounterClockwiseIcon,
  },
  {
    name: "ArrowDownRightIcon",
    label: "Flecha abajo-derecha",
    usage: "CTA de marketing / landing",
    Icon: ArrowDownRightIcon,
  },
  {
    name: "ArrowUpRightIcon",
    label: "Flecha arriba-derecha",
    usage: "Enlaces externos y CTA de marketing",
    Icon: ArrowUpRightIcon,
  },
  {
    name: "BroadcastIcon",
    label: "Emisión",
    usage: "Canales / radio / sync en vivo",
    Icon: BroadcastIcon,
  },
  {
    name: "BuildingsIcon",
    label: "Organización",
    usage: "Organizaciones y espacio de org",
    Icon: BuildingsIcon,
  },
  {
    name: "CalendarDotsIcon",
    label: "Calendario",
    usage: "Programación y fechas",
    Icon: CalendarDotsIcon,
  },
  {
    name: "CaretDownIcon",
    label: "Caret abajo",
    usage: "Select, menús y disparadores",
    Icon: CaretDownIcon,
  },
  {
    name: "CaretRightIcon",
    label: "Caret derecha",
    usage: "Breadcrumb y collapsibles",
    Icon: CaretRightIcon,
  },
  {
    name: "CheckIcon",
    label: "Check",
    usage: "Checkbox, select item, stepper, choice",
    Icon: CheckIcon,
  },
  {
    name: "CheckCircleIcon",
    label: "Éxito",
    usage: "Confirmaciones y estados válidos",
    Icon: CheckCircleIcon,
  },
  {
    name: "CheckSquareOffsetIcon",
    label: "Cola",
    usage: "Placeholder de cola en sidebar colapsada",
    Icon: CheckSquareOffsetIcon,
  },
  {
    name: "CircleNotchIcon",
    label: "Carga",
    usage: "Spinners (con animate-spin)",
    Icon: CircleNotchIcon,
  },
  {
    name: "CopyIcon",
    label: "Copiar",
    usage: "Copiar enlace o token",
    Icon: CopyIcon,
  },
  {
    name: "DotsThreeIcon",
    label: "Más acciones",
    usage: "Menús de fila y breadcrumb ellipsis",
    Icon: DotsThreeIcon,
  },
  {
    name: "EnvelopeSimpleIcon",
    label: "Correo",
    usage: "Campos de email",
    Icon: EnvelopeSimpleIcon,
  },
  {
    name: "EyeIcon",
    label: "Mostrar",
    usage: "Revelar contraseña",
    Icon: EyeIcon,
  },
  {
    name: "EyeSlashIcon",
    label: "Ocultar",
    usage: "Ocultar contraseña",
    Icon: EyeSlashIcon,
  },
  {
    name: "GameControllerIcon",
    label: "Juego / EA Clubs",
    usage: "Clubes EA y espacio personal de juego",
    Icon: GameControllerIcon,
  },
  {
    name: "GearIcon",
    label: "Ajustes",
    usage: "Configuración de cuenta y nav",
    Icon: GearIcon,
  },
  {
    name: "HouseIcon",
    label: "Inicio",
    usage: "Navegación home",
    Icon: HouseIcon,
  },
  {
    name: "InfoIcon",
    label: "Información",
    usage: "Hints, tooltips y ayudas",
    Icon: InfoIcon,
  },
  {
    name: "LinkSimpleIcon",
    label: "Enlace",
    usage: "URLs e invitaciones compartibles",
    Icon: LinkSimpleIcon,
  },
  {
    name: "ListIcon",
    label: "Menú",
    usage: "Abrir navegación móvil (sheet)",
    Icon: ListIcon,
  },
  {
    name: "ListChecksIcon",
    label: "Lista de tareas",
    usage: "Checklist de setup de competición",
    Icon: ListChecksIcon,
  },
  {
    name: "LockIcon",
    label: "Candado",
    usage: "Campos de contraseña",
    Icon: LockIcon,
  },
  {
    name: "MagnifyingGlassIcon",
    label: "Buscar",
    usage: "Inputs de búsqueda",
    Icon: MagnifyingGlassIcon,
  },
  {
    name: "MinusIcon",
    label: "Menos",
    usage: "Checkbox indeterminado",
    Icon: MinusIcon,
  },
  {
    name: "MonitorIcon",
    label: "Monitor",
    usage: "Plataforma genérica / fallback",
    Icon: MonitorIcon,
  },
  {
    name: "PlusIcon",
    label: "Añadir",
    usage: "Crear / acciones primarias",
    Icon: PlusIcon,
  },
  {
    name: "ShieldIcon",
    label: "Escudo",
    usage: "Roles / revisión de onboarding",
    Icon: ShieldIcon,
  },
  {
    name: "SidebarIcon",
    label: "Expandir sidebar",
    usage: "Abrir barra lateral colapsada (alias SidebarExpandIcon si choca con el componente)",
    Icon: SidebarIcon,
  },
  {
    name: "SidebarSimpleIcon",
    label: "Colapsar sidebar",
    usage: "Cerrar barra lateral a icon rail",
    Icon: SidebarSimpleIcon,
  },
  {
    name: "SignpostIcon",
    label: "Señal",
    usage: "Camino / intención en onboarding",
    Icon: SignpostIcon,
  },
  {
    name: "TicketIcon",
    label: "Invitación",
    usage: "Invitaciones a competición",
    Icon: TicketIcon,
  },
  {
    name: "TrayIcon",
    label: "Bandeja vacía",
    usage: "Empty states",
    Icon: TrayIcon,
  },
  {
    name: "TrophyIcon",
    label: "Trofeo",
    usage: "Competiciones y rankings",
    Icon: TrophyIcon,
  },
  {
    name: "UserIcon",
    label: "Usuario",
    usage: "Perfil / jugador individual",
    Icon: UserIcon,
  },
  {
    name: "UsersIcon",
    label: "Usuarios",
    usage: "Equipos",
    Icon: UsersIcon,
  },
  {
    name: "UsersThreeIcon",
    label: "Grupo",
    usage: "Jugadores / plantilla",
    Icon: UsersThreeIcon,
  },
  {
    name: "WarningIcon",
    label: "Advertencia",
    usage: "Alertas de tipo warning",
    Icon: WarningIcon,
  },
  {
    name: "WarningCircleIcon",
    label: "Error / alerta",
    usage: "Field errors y alertas destructivas",
    Icon: WarningCircleIcon,
  },
  {
    name: "XIcon",
    label: "Cerrar",
    usage: "Cerrar dialog / sheet",
    Icon: XIcon,
  },
] as const satisfies readonly FutrobIconEntry[];
