import {
  ArrowCounterClockwiseIcon,
  ArrowDownRightIcon,
  ArrowUpRightIcon,
  ArrowsLeftRightIcon,
  BroadcastIcon,
  BuildingsIcon,
  CalendarDotsIcon,
  CaretDownIcon,
  CaretRightIcon,
  ChartLineUpIcon,
  ChartPieIcon,
  CheckIcon,
  CheckCircleIcon,
  CheckSquareOffsetIcon,
  CircleNotchIcon,
  CopyIcon,
  DotsThreeIcon,
  EnvelopeSimpleIcon,
  EqualsIcon,
  EyeIcon,
  EyeSlashIcon,
  GameControllerIcon,
  GaugeIcon,
  GearIcon,
  HandshakeIcon,
  HouseIcon,
  InfoIcon,
} from "@phosphor-icons/react";
import type { FutrobIconEntry } from "./catalog.ts";

/** First half of the Phosphor inventory used by `@futrob/ui` and `apps/web`. */
export const FUTROB_ICON_CATALOG_A = [
  {
    name: "ArrowCounterClockwiseIcon",
    label: "Reintentar",
    usage: "Acciones de refresh / reintentar",
    Icon: ArrowCounterClockwiseIcon,
  },
  {
    name: "ArrowDownRightIcon",
    label: "Flecha abajo-derecha",
    usage: "CTA de marketing / landing",
    Icon: ArrowDownRightIcon,
  },
  {
    name: "ArrowUpRightIcon",
    label: "Flecha arriba-derecha",
    usage: "Enlaces externos y CTA de marketing",
    Icon: ArrowUpRightIcon,
  },
  {
    name: "ArrowsLeftRightIcon",
    label: "Flechas horizontales",
    usage: "Contrapropuesta en la cola de tareas",
    Icon: ArrowsLeftRightIcon,
  },
  {
    name: "BroadcastIcon",
    label: "Emisión",
    usage: "Canales / radio / sync en vivo",
    Icon: BroadcastIcon,
  },
  {
    name: "BuildingsIcon",
    label: "Organización",
    usage: "Organizaciones y espacio de org",
    Icon: BuildingsIcon,
  },
  {
    name: "CalendarDotsIcon",
    label: "Calendario",
    usage: "Programación y fechas",
    Icon: CalendarDotsIcon,
  },
  {
    name: "CaretDownIcon",
    label: "Caret abajo",
    usage: "Select, menús y disparadores",
    Icon: CaretDownIcon,
  },
  {
    name: "CaretRightIcon",
    label: "Caret derecha",
    usage: "Breadcrumb y collapsibles",
    Icon: CaretRightIcon,
  },
  {
    name: "ChartLineUpIcon",
    label: "G+A",
    usage: "Goles más asistencias en Mis partidos",
    Icon: ChartLineUpIcon,
  },
  {
    name: "ChartPieIcon",
    label: "Récord",
    usage: "Récord V–E–D en Mis estadísticas",
    Icon: ChartPieIcon,
  },
  {
    name: "CheckIcon",
    label: "Check",
    usage: "Checkbox, select item, stepper, choice",
    Icon: CheckIcon,
  },
  {
    name: "CheckCircleIcon",
    label: "Éxito",
    usage: "Confirmaciones y estados válidos",
    Icon: CheckCircleIcon,
  },
  {
    name: "CheckSquareOffsetIcon",
    label: "Tareas",
    usage: "Placeholder de tareas en sidebar colapsada",
    Icon: CheckSquareOffsetIcon,
  },
  {
    name: "CircleNotchIcon",
    label: "Carga",
    usage: "Spinners (con animate-spin)",
    Icon: CircleNotchIcon,
  },
  {
    name: "CopyIcon",
    label: "Copiar",
    usage: "Copiar enlace o token",
    Icon: CopyIcon,
  },
  {
    name: "DotsThreeIcon",
    label: "Más acciones",
    usage: "Menús de fila y breadcrumb ellipsis",
    Icon: DotsThreeIcon,
  },
  {
    name: "EnvelopeSimpleIcon",
    label: "Correo",
    usage: "Campos de email",
    Icon: EnvelopeSimpleIcon,
  },
  {
    name: "EqualsIcon",
    label: "Igual",
    usage: "Empates en Mis partidos",
    Icon: EqualsIcon,
  },
  {
    name: "EyeIcon",
    label: "Mostrar",
    usage: "Revelar contraseña",
    Icon: EyeIcon,
  },
  {
    name: "EyeSlashIcon",
    label: "Ocultar",
    usage: "Ocultar contraseña",
    Icon: EyeSlashIcon,
  },
  {
    name: "GameControllerIcon",
    label: "Juego / EA Clubs",
    usage: "Clubes EA y espacio personal de juego",
    Icon: GameControllerIcon,
  },
  {
    name: "GaugeIcon",
    label: "Rating",
    usage: "Rating de aparición en Mis partidos",
    Icon: GaugeIcon,
  },
  {
    name: "GearIcon",
    label: "Ajustes",
    usage: "Configuración de cuenta y nav",
    Icon: GearIcon,
  },
  {
    name: "HandshakeIcon",
    label: "Asistencia",
    usage: "Asistencias en Mis partidos y Mis estadísticas",
    Icon: HandshakeIcon,
  },
  {
    name: "HouseIcon",
    label: "Inicio",
    usage: "Navegación home",
    Icon: HouseIcon,
  },
  {
    name: "InfoIcon",
    label: "Información",
    usage: "Hints, tooltips y ayudas",
    Icon: InfoIcon,
  },
] as const satisfies readonly FutrobIconEntry[];
