import type { Icon } from "@phosphor-icons/react";
import {
  ArrowCounterClockwise,
  ArrowDownRight,
  ArrowUpRight,
  Broadcast,
  Buildings,
  CalendarDots,
  CaretDown,
  CaretRight,
  Check,
  CheckCircle,
  CheckSquareOffset,
  CircleNotch,
  Copy,
  DotsThree,
  EnvelopeSimple,
  Eye,
  EyeSlash,
  GameController,
  Gear,
  House,
  Info,
  LinkSimple,
  List,
  ListChecks,
  Lock,
  MagnifyingGlass,
  Minus,
  Monitor,
  Plus,
  Shield,
  Sidebar,
  SidebarSimple,
  Signpost,
  Ticket,
  Tray,
  Trophy,
  User,
  Users,
  UsersThree,
  Warning,
  WarningCircle,
  X,
} from "@phosphor-icons/react";

export type FutrobIconEntry = {
  readonly name: string;
  readonly label: string;
  readonly usage: string;
  readonly Icon: Icon;
};

/**
 * Every Phosphor icon referenced by `@futrob/ui` or `apps/web` presentation.
 * Keep this list in sync when adding or renaming product icons.
 */
export const FUTROB_ICON_CATALOG = [
  {
    name: "ArrowCounterClockwise",
    label: "Reintentar",
    usage: "Acciones de refresh / reintentar",
    Icon: ArrowCounterClockwise,
  },
  {
    name: "ArrowDownRight",
    label: "Flecha abajo-derecha",
    usage: "CTA de marketing / landing",
    Icon: ArrowDownRight,
  },
  {
    name: "ArrowUpRight",
    label: "Flecha arriba-derecha",
    usage: "Enlaces externos y CTA de marketing",
    Icon: ArrowUpRight,
  },
  {
    name: "Broadcast",
    label: "Emisión",
    usage: "Canales / radio / sync en vivo",
    Icon: Broadcast,
  },
  {
    name: "Buildings",
    label: "Organización",
    usage: "Organizaciones y espacio de org",
    Icon: Buildings,
  },
  {
    name: "CalendarDots",
    label: "Calendario",
    usage: "Programación y fechas",
    Icon: CalendarDots,
  },
  {
    name: "CaretDown",
    label: "Caret abajo",
    usage: "Select, menús y disparadores",
    Icon: CaretDown,
  },
  {
    name: "CaretRight",
    label: "Caret derecha",
    usage: "Breadcrumb y collapsibles",
    Icon: CaretRight,
  },
  {
    name: "Check",
    label: "Check",
    usage: "Checkbox, select item, stepper, choice",
    Icon: Check,
  },
  {
    name: "CheckCircle",
    label: "Éxito",
    usage: "Confirmaciones y estados válidos",
    Icon: CheckCircle,
  },
  {
    name: "CheckSquareOffset",
    label: "Cola",
    usage: "Placeholder de cola en sidebar colapsada",
    Icon: CheckSquareOffset,
  },
  {
    name: "CircleNotch",
    label: "Carga",
    usage: "Spinners (con animate-spin)",
    Icon: CircleNotch,
  },
  {
    name: "Copy",
    label: "Copiar",
    usage: "Copiar enlace o token",
    Icon: Copy,
  },
  {
    name: "DotsThree",
    label: "Más acciones",
    usage: "Menús de fila y breadcrumb ellipsis",
    Icon: DotsThree,
  },
  {
    name: "EnvelopeSimple",
    label: "Correo",
    usage: "Campos de email",
    Icon: EnvelopeSimple,
  },
  {
    name: "Eye",
    label: "Mostrar",
    usage: "Revelar contraseña",
    Icon: Eye,
  },
  {
    name: "EyeSlash",
    label: "Ocultar",
    usage: "Ocultar contraseña",
    Icon: EyeSlash,
  },
  {
    name: "GameController",
    label: "Juego / EA Clubs",
    usage: "Clubes EA y espacio personal de juego",
    Icon: GameController,
  },
  {
    name: "Gear",
    label: "Ajustes",
    usage: "Configuración de cuenta y nav",
    Icon: Gear,
  },
  {
    name: "House",
    label: "Inicio",
    usage: "Navegación home",
    Icon: House,
  },
  {
    name: "Info",
    label: "Información",
    usage: "Hints, tooltips y ayudas",
    Icon: Info,
  },
  {
    name: "LinkSimple",
    label: "Enlace",
    usage: "URLs e invitaciones compartibles",
    Icon: LinkSimple,
  },
  {
    name: "List",
    label: "Menú",
    usage: "Abrir navegación móvil (sheet)",
    Icon: List,
  },
  {
    name: "ListChecks",
    label: "Lista de tareas",
    usage: "Checklist de setup de competición",
    Icon: ListChecks,
  },
  {
    name: "Lock",
    label: "Candado",
    usage: "Campos de contraseña",
    Icon: Lock,
  },
  {
    name: "MagnifyingGlass",
    label: "Buscar",
    usage: "Inputs de búsqueda",
    Icon: MagnifyingGlass,
  },
  {
    name: "Minus",
    label: "Menos",
    usage: "Checkbox indeterminado",
    Icon: Minus,
  },
  {
    name: "Monitor",
    label: "Monitor",
    usage: "Plataforma genérica / fallback",
    Icon: Monitor,
  },
  {
    name: "Plus",
    label: "Añadir",
    usage: "Crear / acciones primarias",
    Icon: Plus,
  },
  {
    name: "Shield",
    label: "Escudo",
    usage: "Roles / revisión de onboarding",
    Icon: Shield,
  },
  {
    name: "Sidebar",
    label: "Expandir sidebar",
    usage: "Abrir barra lateral colapsada (alias SidebarExpandIcon si choca con el componente)",
    Icon: Sidebar,
  },
  {
    name: "SidebarSimple",
    label: "Colapsar sidebar",
    usage: "Cerrar barra lateral a icon rail",
    Icon: SidebarSimple,
  },
  {
    name: "Signpost",
    label: "Señal",
    usage: "Camino / intención en onboarding",
    Icon: Signpost,
  },
  {
    name: "Ticket",
    label: "Invitación",
    usage: "Invitaciones a competición",
    Icon: Ticket,
  },
  {
    name: "Tray",
    label: "Bandeja vacía",
    usage: "Empty states",
    Icon: Tray,
  },
  {
    name: "Trophy",
    label: "Trofeo",
    usage: "Competiciones y rankings",
    Icon: Trophy,
  },
  {
    name: "User",
    label: "Usuario",
    usage: "Perfil / jugador individual",
    Icon: User,
  },
  {
    name: "Users",
    label: "Usuarios",
    usage: "Equipos",
    Icon: Users,
  },
  {
    name: "UsersThree",
    label: "Grupo",
    usage: "Jugadores / plantilla",
    Icon: UsersThree,
  },
  {
    name: "Warning",
    label: "Advertencia",
    usage: "Alertas de tipo warning",
    Icon: Warning,
  },
  {
    name: "WarningCircle",
    label: "Error / alerta",
    usage: "Field errors y alertas destructivas",
    Icon: WarningCircle,
  },
  {
    name: "X",
    label: "Cerrar",
    usage: "Cerrar dialog / sheet",
    Icon: X,
  },
] as const satisfies readonly FutrobIconEntry[];
