import * as stylex from "@stylexjs/stylex";

/**
 * Semantic colors. Values point at `tokens.css` so `.dark` / `[data-theme="dark"]`
 * keep working without `createTheme`. Do not hardcode OKLCH here.
 */
export const colors = stylex.defineVars({
  background: "var(--background)",
  foreground: "var(--foreground)",
  surface: "var(--surface)",
  surfaceRaised: "var(--surface-raised)",
  card: "var(--card)",
  cardForeground: "var(--card-foreground)",
  popover: "var(--popover)",
  popoverForeground: "var(--popover-foreground)",
  primary: "var(--primary)",
  primaryHover: "var(--primary-hover)",
  primaryForeground: "var(--primary-foreground)",
  secondary: "var(--secondary)",
  secondaryHover: "var(--secondary-hover)",
  secondaryForeground: "var(--secondary-foreground)",
  muted: "var(--muted)",
  mutedForeground: "var(--muted-foreground)",
  accent: "var(--accent)",
  accentForeground: "var(--accent-foreground)",
  border: "var(--border)",
  borderSubtle: "var(--border-subtle)",
  borderStrong: "var(--border-strong)",
  input: "var(--input)",
  ring: "var(--ring)",
  success: "var(--success)",
  successForeground: "var(--success-foreground)",
  approved: "var(--approved)",
  approvedForeground: "var(--approved-foreground)",
  approvedSubtle: "var(--approved-subtle)",
  approvedSubtleForeground: "var(--approved-subtle-foreground)",
  warning: "var(--warning)",
  warningForeground: "var(--warning-foreground)",
  danger: "var(--danger)",
  dangerForeground: "var(--danger-foreground)",
  destructive: "var(--destructive)",
  destructiveForeground: "var(--destructive-foreground)",
  info: "var(--info)",
  infoForeground: "var(--info-foreground)",
  emphasis: "var(--emphasis)",
  emphasisForeground: "var(--emphasis-foreground)",
  sidebar: "var(--sidebar)",
  sidebarForeground: "var(--sidebar-foreground)",
  sidebarPrimary: "var(--sidebar-primary)",
  sidebarPrimaryForeground: "var(--sidebar-primary-foreground)",
  sidebarAccent: "var(--sidebar-accent)",
  sidebarAccentForeground: "var(--sidebar-accent-foreground)",
  sidebarBorder: "var(--sidebar-border)",
  sidebarRing: "var(--sidebar-ring)",
  brand500: "var(--brand-500)",
  brand700: "var(--brand-700)",
  neutral950: "var(--neutral-950)",
});
