import * as stylex from "@stylexjs/stylex";
import { colors } from "@futrob/ui/styles/tokens.stylex";
import { media } from "@futrob/ui/styles/media.stylex";

export const styles = stylex.create({
  slot: {
    display: "flex",
    flexDirection: "column",
    alignSelf: "stretch",
    flexGrow: 1,
    minWidth: 0,
  },
  heroSlot: {
    minHeight: "22rem",
  },
  sideSlot: {
    minHeight: "10rem",
  },
  bottomSlot: {
    minHeight: "18rem",
  },
  heroFill: {
    display: "flex",
    width: "100%",
    flexGrow: 1,
    flexDirection: "column",
    alignItems: "flex-start",
    gap: "1rem",
    paddingTop: "1.5rem",
    paddingInline: "1.5rem",
    paddingBottom: "1rem",
  },
  heroHeader: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: "0.5rem",
  },
  heroTitle: {
    width: "14rem",
    height: "1.75rem",
  },
  roundBadge: {
    width: "11rem",
    height: "1.5rem",
    borderRadius: "var(--corner-full)",
  },
  matchup: {
    display: "flex",
    width: "100%",
    flexGrow: 1,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  fixtureCrest: {
    borderRadius: "var(--corner-full)",
    flexShrink: 0,
  },
  fixtureName: {
    width: "6rem",
    height: "0.875rem",
  },
  vs: {
    width: "2.25rem",
    height: "1.5rem",
  },
  when: {
    width: "7.5rem",
    height: "0.875rem",
  },
  pending: {
    width: "6.5rem",
    height: "1.5rem",
    borderRadius: "var(--corner-full)",
  },
  title: {
    width: "11rem",
    height: "1.75rem",
  },
  subtitle: {
    width: "70%",
    maxWidth: "22rem",
    height: "0.875rem",
  },
  heroCta: {
    width: "10rem",
    height: "2.5rem",
    borderRadius: "var(--corner-full)",
    alignSelf: "center",
    marginTop: "auto",
  },
  artStack: {
    display: "flex",
    width: "100%",
    flexGrow: 1,
    flexDirection: "column",
    alignItems: "flex-start",
    gap: "2rem",
    minHeight: "14rem",
  },
  artFocus: {
    display: "flex",
    width: "100%",
    flexGrow: 1,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "1rem",
  },
  artWide: {
    width: {
      default: "12rem",
      [media.md]: "16rem",
      [media.lg]: "20rem",
    },
    height: "auto",
    aspectRatio: "532 / 253",
    flexShrink: 0,
    borderRadius: "var(--corner-lg)",
  },
  artCta: {
    width: "10rem",
    height: "2.5rem",
    borderRadius: "var(--corner-full)",
  },
  banner: {
    display: "flex",
    alignItems: "flex-start",
    gap: "0.75rem",
  },
  emptyCentered: {
    display: "flex",
    flexGrow: 1,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.75rem",
    textAlign: "center",
  },
  emptyCopy: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "0.25rem",
    width: "100%",
    maxWidth: "24rem",
  },
  sideBody: {
    display: "flex",
    flexGrow: 1,
    flexDirection: "column",
    gap: "0.75rem",
  },
  sideCopy: {
    display: "flex",
    minWidth: 0,
    flexGrow: 1,
    flexDirection: "column",
    gap: "0.5rem",
  },
  crests: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "1.5rem",
    width: "100%",
  },
  crest: {
    width: "4rem",
    height: "4rem",
    borderRadius: "var(--corner-full)",
    flexShrink: 0,
  },
  axis: {
    width: "2.5rem",
    height: "1rem",
  },
  appearance: {
    width: "100%",
    height: "2.75rem",
    borderRadius: "var(--corner-full)",
  },
  row: {
    display: "flex",
    alignItems: "center",
    gap: "0.75rem",
  },
  avatar: {
    width: "2.5rem",
    height: "2.5rem",
    borderRadius: "var(--corner-full)",
    flexShrink: 0,
  },
  grow: {
    flex: 1,
    height: "0.75rem",
  },
  chevron: {
    width: "1rem",
    height: "1rem",
    flexShrink: 0,
  },
  header: {
    display: "flex",
    width: "100%",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "0.75rem",
  },
  headerAction: {
    width: "5rem",
    height: "0.75rem",
    flexShrink: 0,
  },
  bottomBody: {
    display: "flex",
    flexGrow: 1,
    flexDirection: "column",
    justifyContent: "center",
    gap: "2rem",
  },
  list: {
    display: "flex",
    flexGrow: 1,
    flexDirection: "column",
    justifyContent: "center",
    gap: "0.75rem",
  },
  listRow: {
    display: "flex",
    minHeight: "2.75rem",
    alignItems: "center",
    gap: "0.75rem",
  },
  stats: {
    display: "grid",
    width: "100%",
    gap: "1rem",
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      [media.lg]: "repeat(4, minmax(0, 1fr))",
    },
  },
  stat: {
    display: "flex",
    alignItems: "center",
    minWidth: 0,
    gap: "0.75rem",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: "var(--corner-lg)",
    backgroundColor: colors.surface,
    padding: "1rem",
  },
  icon: {
    width: "3rem",
    height: "3rem",
    flexShrink: 0,
    borderRadius: "var(--corner-full)",
  },
});
