import { ref, fallbackRef, type TokenMap } from "./token.ts";

/** Light semantic theme — mirrors the `:root` block in `packages/ui/src/tokens.css`. */
export const LIGHT_THEME: TokenMap = {
  background: ref("neutral-50"),
  foreground: ref("neutral-950"),
  surface: ref("neutral-0"),
  "surface-raised": ref("neutral-0"),
  card: ref("neutral-0"),
  "card-foreground": ref("neutral-950"),
  popover: ref("neutral-0"),
  "popover-foreground": ref("neutral-950"),
  primary: ref("brand-700"),
  "primary-hover": ref("brand-800"),
  "primary-foreground": ref("neutral-0"),
  secondary: ref("neutral-200"),
  "secondary-hover": ref("neutral-300"),
  "secondary-foreground": ref("neutral-900"),
  muted: ref("neutral-100"),
  "muted-foreground": ref("neutral-600"),
  accent: ref("brand-100"),
  "accent-foreground": ref("brand-900"),
  "border-subtle": ref("neutral-200"),
  border: ref("neutral-300"),
  "border-strong": ref("neutral-450"),
  input: ref("neutral-450"),
  ring: ref("brand-600"),
  success: ref("brand-700"),
  "success-foreground": ref("neutral-0"),
  approved: ref("brand-800"),
  "approved-foreground": ref("neutral-0"),
  "approved-subtle": ref("brand-100"),
  "approved-subtle-foreground": ref("brand-900"),
  warning: ref("amber-700"),
  "warning-foreground": ref("neutral-0"),
  danger: ref("red-700"),
  "danger-foreground": ref("neutral-0"),
  // shadcn alias — prefer `danger` in Futrob product code
  destructive: ref("danger"),
  "destructive-foreground": ref("danger-foreground"),
  info: ref("blue-700"),
  "info-foreground": ref("neutral-0"),
  // Categorical highlight — not a status. Distinct from brand, info, warning, danger.
  emphasis: ref("violet-700"),
  "emphasis-foreground": ref("neutral-0"),
  sidebar: ref("surface"),
  "sidebar-foreground": ref("foreground"),
  "sidebar-primary": ref("primary"),
  "sidebar-primary-foreground": ref("primary-foreground"),
  "sidebar-accent": ref("accent"),
  "sidebar-accent-foreground": ref("accent-foreground"),
  "sidebar-border": ref("border"),
  "sidebar-ring": ref("ring"),
  "status-sync": ref("blue-700"),
  "status-selection": ref("amber-700"),
  "status-approved": ref("approved"),
  "status-dispute": ref("red-700"),
  "status-cancelled": ref("neutral-600"),
  "chart-1": ref("brand-600"),
  "chart-2": fallbackRef("blue-600", "blue-500"),
  "chart-3": fallbackRef("amber-600", "amber-500"),
  "chart-4": fallbackRef("red-600", "red-500"),
  "chart-5": ref("neutral-600"),
};
