/** @deprecated Import from `@futrob/ea-clubs` — re-export kept for local adapter paths. */
export {
  eaNumeric,
  eaNumericRequired,
  eaIdAsString,
  eaCustomKitSchema,
  eaClubInfoSchema,
  eaLeaderboardEntrySchema,
  eaSearchClubsResponseSchema,
  eaClubInfoMapSchema,
  eaMatchClubSchema,
  eaPlayerMatchStatsSchema,
  eaClubMatchSchema,
  eaClubMatchesResponseSchema,
  type EaCustomKit,
  type EaClubInfo,
  type EaLeaderboardEntry,
  type EaClubInfoMap,
  type EaMatchClub,
  type EaPlayerMatchStats,
  type EaClubMatch,
} from "@futrob/ea-clubs";
