/**
 * Renders `packages/ui/src/tokens.css` from the typed token data in
 * `@futrob/ui-tokens`. The CSS file is a build artifact: edit tokens here
 * (TS), then run `npm run generate:css -w @futrob/ui-tokens`.
 *
 * Run: node scripts/generate-css.mjs [--check]
 * --check verifies the committed artifact is up to date (CI-friendly).
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const workspaceRoot = path.resolve(packageRoot, "../..");
const outputPath = path.join(workspaceRoot, "packages/ui/src/tokens.css");

const {
  AMBER_SCALE,
  BLUE_SCALE,
  BRAND_SCALE,
  CONTROL_TOKENS,
  CORNER_TOKENS,
  DARK_THEME,
  LAYERING_TOKENS,
  LIGHT_THEME,
  MOTION_TOKENS,
  NEUTRAL_SCALE,
  RED_SCALE,
  SPACING_TOKENS,
  TYPOGRAPHY_TOKENS,
  VIOLET_SCALE,
  oklchToken,
  toCssDeclaration,
} = await import(path.join(workspaceRoot, "packages/ui-tokens/src/index.ts"));

function declarations(tokens, inlineComments = {}) {
  return Object.entries(tokens).map(([name, value]) => {
    const comment = inlineComments[name];
    const declaration = `  ${toCssDeclaration(name, value)}`;
    return comment === undefined ? declaration : `  /* ${comment} */\n${declaration}`;
  });
}

/** Raw scales are stored as plain Oklch records; render them as oklch tokens. */
function scaleDeclarations(prefix, scale) {
  return Object.entries(scale).map(
    ([stop, color]) => `  ${toCssDeclaration(`${prefix}-${stop}`, oklchToken(color))}`,
  );
}

function section(comment, lines) {
  const out = [];
  if (comment !== null) {
    out.push(`  /* ${comment} */`);
  }
  out.push(...lines);
  return out;
}

const typographyBase = {};
const typographyRoles = {};
for (const [name, value] of Object.entries(TYPOGRAPHY_TOKENS)) {
  if (name.startsWith("typo-")) {
    typographyRoles[name] = value;
  } else {
    typographyBase[name] = value;
  }
}

/** Inline comments attached to specific light-theme declarations. */
const LIGHT_THEME_COMMENTS = {
  destructive: "shadcn alias — prefer --danger in Futrob product code",
  emphasis: "Categorical highlight — not a status. Distinct from brand, info, warning, danger.",
};

const rootBody = [
  section("Pitch Ops — raw brand scale", scaleDeclarations("brand", BRAND_SCALE)),
  [""],
  section("Warm field-tinted neutrals", scaleDeclarations("neutral", NEUTRAL_SCALE)),
  [""],
  section("Semantic accent scales", scaleDeclarations("red", RED_SCALE)),
  [""],
  section(null, scaleDeclarations("amber", AMBER_SCALE)),
  [""],
  section(null, scaleDeclarations("blue", BLUE_SCALE)),
  [""],
  section(
    "Categorical highlight scale. Consume via --emphasis.",
    scaleDeclarations("violet", VIOLET_SCALE),
  ),
  [""],
  section(
    "Typography — Manrope; canonical weights 400 / 500 / 600 / 700",
    declarations(typographyBase),
  ),
  [""],
  section(
    "Typography roles (consumed by StyleX `typography.*` and mobile StyleSheet)",
    declarations(typographyRoles),
  ),
  [""],
  section("Spacing and geometry", declarations(SPACING_TOKENS)),
  section(
    "Corner ramp. Single source; apps map it onto their platform radius namespace.",
    declarations(CORNER_TOKENS),
  ),
  [""],
  section(
    "Universal controls. `dense` is the only compact mode and never drops below 36px.",
    declarations(CONTROL_TOKENS),
  ),
  [""],
  section(
    "Flat/line controls use borders. Elevated surfaces use StyleX `elevation.*`\n     (never pair with border/ring on the same element).",
    [],
  ),
  [""],
  section("Motion", declarations(MOTION_TOKENS)),
  [""],
  section("Layering", declarations(LAYERING_TOKENS)),
  [""],
  section("Light semantic theme", [
    "  color-scheme: light;",
    ...declarations(LIGHT_THEME, LIGHT_THEME_COMMENTS),
  ]),
];

const darkBody = [
  section("Dark semantic theme", ["  color-scheme: dark;", ...declarations(DARK_THEME)]),
];

const css = [
  "/* GENERATED by @futrob/ui-tokens (scripts/generate-css.mjs). Do not edit by hand:",
  "   change tokens in packages/ui-tokens/src and run `npm run generate:css -w @futrob/ui-tokens`. */",
  "",
  ":root {",
  ...rootBody.flat(),
  "}",
  "",
  ".dark,",
  '[data-theme="dark"] {',
  ...darkBody.flat(),
  "}",
  "",
  "@media (prefers-reduced-motion: reduce) {",
  "  :root {",
  "    --duration-fast: 0ms;",
  "    --duration-normal: 0ms;",
  "    --duration-slow: 0ms;",
  "  }",
  "}",
  "",
].join("\n");

if (process.argv.includes("--check")) {
  const current = readFileSync(outputPath, "utf8");
  if (current !== css) {
    console.error(
      "tokens.css is out of date with @futrob/ui-tokens. Run `npm run generate:css -w @futrob/ui-tokens`.",
    );
    process.exit(1);
  }
  process.stdout.write("tokens.css is up to date\n");
} else {
  writeFileSync(outputPath, css);
  process.stdout.write(`generated ${path.relative(workspaceRoot, outputPath)}\n`);
}
