/**
 * Renders `packages/ui/src/tokens.css` from the typed token data in
 * `@futrob/ui-tokens`. The CSS file is a build artifact: edit tokens here
 * (TS), then run `npm run generate:css -w @futrob/ui-tokens`.
 *
 * Run: node scripts/generate-css.mjs [--check]
 * --check verifies the committed artifact is up to date (CI-friendly).
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const workspaceRoot = path.resolve(packageRoot, "../..");
const outputPath = path.join(workspaceRoot, "packages/ui/src/tokens.css");

const { ROOT_TOKENS, GRAPHITE_LIME_THEME, toCssDeclaration } = await import(
  path.join(workspaceRoot, "packages/ui-tokens/src/index.ts")
);

function declarations(tokens, inlineComments = {}) {
  return Object.entries(tokens).map(([name, value]) => {
    const comment = inlineComments[name];
    const declaration = `  ${toCssDeclaration(name, value)}`;
    return comment === undefined ? declaration : `  /* ${comment} */\n${declaration}`;
  });
}

const css = [
  "/* GENERATED by @futrob/ui-tokens (scripts/generate-css.mjs). Do not edit by hand:",
  "   change tokens in packages/ui-tokens/src and run `npm run generate:css -w @futrob/ui-tokens`. */",
  "",
  ":root {",
  "  color-scheme: dark;",
  ...declarations(ROOT_TOKENS),
  "}",
  "",
  ".light,",
  '[data-theme="light"],',
  ".dark,",
  '[data-theme="dark"] {',
  "  color-scheme: dark;",
  ...declarations(GRAPHITE_LIME_THEME),
  "}",
  "",
  "@media (prefers-reduced-motion: reduce) {",
  "  :root {",
  "    --duration-fast: 0ms;",
  "    --duration-normal: 0ms;",
  "    --duration-slow: 0ms;",
  "  }",
  "}",
  "",
].join("\n");

if (process.argv.includes("--check")) {
  const current = readFileSync(outputPath, "utf8");
  if (current !== css) {
    console.error(
      "tokens.css is out of date with @futrob/ui-tokens. Run `npm run generate:css -w @futrob/ui-tokens`.",
    );
    process.exit(1);
  }
  process.stdout.write("tokens.css is up to date\n");
} else {
  writeFileSync(outputPath, css);
  process.stdout.write(`generated ${path.relative(workspaceRoot, outputPath)}\n`);
}
